using Qora.Ir;
using Qora.Ir.Mir;

namespace Qora.Tests;

public sealed class MirQasmEmitterTests
{
    private static readonly MirQasmScalarType Int =
        new(MirQasmScalarKind.Int);

    [Fact]
    public void EmitsTheCompleteTargetVocabularyWithoutConsultingCompilerState()
    {
        var program = CompleteProgram();

        var text = MirQasmEmitter.Emit(program);

        Assert.StartsWith(
            $"// generated by Qora v{QoraVersion.Value}\n" +
            "OPENQASM 3;\ninclude \"stdgates.inc\";",
            text.ReplaceLineEndings("\n"));
        Assert.Contains("// Qora: emitted only from the immutable target tree", text);

        Assert.Contains("def z_helper(int source_value) -> int", text);
        Assert.Contains("return source_value + 1;", text);
        Assert.Contains("def a_worker(qubit worker_target)", text);
        Assert.Contains("rx(pi / 2) worker_target;", text);
        Assert.Contains(
            "def m_caller(qubit caller_target, int caller_count)",
            text);
        Assert.Contains("int next_result = z_helper(caller_count);", text);
        Assert.Contains("a_worker(caller_target);", text);

        Assert.Contains("qubit[2] q_final;", text);
        Assert.Contains("bit measured_final;", text);
        Assert.Contains("array[int, 2] values_final = {1, 2};", text);
        Assert.Contains(
            "int index_final = z_helper(sizeof(values_final)) + uint[2](\"01\");",
            text);
        Assert.Contains("bool bool_final;", text);
        Assert.Contains("uint uint_final;", text);
        Assert.Contains("float float_final;", text);
        Assert.Contains("angle angle_final;", text);
        Assert.Contains("bit[3] bits_final;", text);
        Assert.Contains("values_final[index_final] = -index_final;", text);
        Assert.Contains("measured_final = measure q_final[0];", text);
        Assert.Contains("inv @ ctrl @ x q_final[0], q_final[1];", text);
        Assert.Contains("if (measured_final == 1) {", text);
        Assert.Contains("m_caller(q_final[0], index_final);", text);
        Assert.Contains("while (index_final < 2) {", text);
        Assert.Contains("index_final = index_final + 1;", text);
        Assert.Contains("break;", text);
    }

    [Fact]
    public void OrdersDefinitionsByTypedCallableIdsRatherThanNamesOrInputOrder()
    {
        var program = CompleteProgram();

        var text = MirQasmEmitter.Emit(program);
        var helper = text.IndexOf("def z_helper", StringComparison.Ordinal);
        var worker = text.IndexOf("def a_worker", StringComparison.Ordinal);
        var caller = text.IndexOf("def m_caller", StringComparison.Ordinal);

        Assert.True(helper >= 0);
        Assert.True(worker >= 0);
        Assert.True(caller >= 0);
        Assert.True(helper < caller);
        Assert.True(worker < caller);
        Assert.Equal(
            new[]
            {
                new MirQasmCallableId(0),
                new MirQasmCallableId(1),
                new MirQasmCallableId(2),
            },
            MirQasmEmitter
                .OrderDefinitions(program.Definitions)
                .Select(definition => definition.Id));
    }

    [Fact]
    public void EmitsFinalReadOnlyAndMutableArrayParameterContracts()
    {
        var definition = new MirQasmCallableDefinition(
            new MirQasmCallableId(0),
            "array_contract",
            new[]
            {
                new MirQasmParameter(
                    new MirQasmParameterId(0),
                    "source_final",
                    new MirQasmArrayType(Int),
                    MirQasmParameterAccess.ReadOnly),
                new MirQasmParameter(
                    new MirQasmParameterId(1),
                    "destination_final",
                    new MirQasmArrayType(
                        new MirQasmScalarType(MirQasmScalarKind.Float)),
                    MirQasmParameterAccess.Mutable),
            },
            returnType: null,
            new MirQasmStatement[]
            {
                new MirQasmReturnStatement(),
            });
        var program = new MirOpenQasmTargetProgram(
            Array.Empty<MirQasmStatement>(),
            new[] { definition });

        var text = MirQasmEmitter.Emit(program);

        Assert.Contains(
            "def array_contract(" +
            "readonly array[int, #dim = 1] source_final, " +
            "mutable array[float, #dim = 1] destination_final)",
            text);
    }

    [Fact]
    public void TargetProgramCarriesNoMirSnapshotIdentity()
    {
        var program = new MirOpenQasmTargetProgram(
            Array.Empty<MirQasmStatement>(),
            Array.Empty<MirQasmCallableDefinition>());

        Assert.Equal(
            $"// generated by Qora v{QoraVersion.Value}\n" +
            "OPENQASM 3;\ninclude \"stdgates.inc\";",
            MirQasmEmitter.Emit(program).ReplaceLineEndings("\n"));
        Assert.DoesNotContain(
            typeof(MirOpenQasmTargetProgram).GetProperties(),
            property => property.PropertyType == typeof(MirSnapshotId));
        Assert.DoesNotContain(
            typeof(MirOpenQasmTargetProgram).GetFields(
                System.Reflection.BindingFlags.Instance
                | System.Reflection.BindingFlags.Public
                | System.Reflection.BindingFlags.NonPublic),
            field => field.FieldType == typeof(MirSnapshotId));
    }

    [Fact]
    public void ProgramFreezesAllInputCollections()
    {
        var statements = new List<MirQasmStatement>();
        var notes = new List<string> { "first" };
        var definitions = new List<MirQasmCallableDefinition>();

        var program = new MirOpenQasmTargetProgram(
            statements,
            definitions,
            notes);

        statements.Add(
            new MirQasmBreakStatement());
        notes.Add("second");
        definitions.Add(
            new MirQasmCallableDefinition(
                new MirQasmCallableId(1),
                "late_definition",
                Array.Empty<MirQasmParameter>(),
                returnType: null,
                Array.Empty<MirQasmStatement>()));

        Assert.Empty(program.EntryBody);
        Assert.Equal(new[] { "first" }, program.Notes);
        Assert.Empty(program.Definitions);
    }

    [Fact]
    public void RejectsMissingTypedBindingReferences()
    {
        var entryBody = new MirQasmStatement[]
        {
            new MirQasmValueDeclarationStatement(
                new MirQasmDeclarationId(0),
                "value_final",
                Int,
                new MirQasmDeclarationReferenceExpression(
                    new MirQasmDeclarationId(99))),
        };

        var error = Assert.Throws<ArgumentException>(
            () => new MirOpenQasmTargetProgram(
                entryBody,
                Array.Empty<MirQasmCallableDefinition>()));

        Assert.Contains("missing declaration oqd99", error.Message);
    }

    [Fact]
    public void RejectsModifiersOnUserOperationsBecauseTheyMustBeMaterializedInMir()
    {
        var error = Assert.Throws<ArgumentException>(
            () => new MirQasmQuantumApplyStatement(
                new MirQasmUserQuantumTarget(new MirQasmCallableId(1)),
                Array.Empty<MirQasmExpression>(),
                Array.Empty<MirQasmExpression>(),
                new[] { MirQasmQuantumModifier.Inverse }));

        Assert.Contains("already have inverse/control materialized", error.Message);
    }

    [Fact]
    public void RejectsRecursiveDefinitionCyclesInsteadOfGuessingAnOrder()
    {
        var firstId = new MirQasmCallableId(0);
        var secondId = new MirQasmCallableId(1);
        var first = FunctionReturningCall(firstId, "first_final", secondId);
        var second = FunctionReturningCall(secondId, "second_final", firstId);
        var program = new MirOpenQasmTargetProgram(
            Array.Empty<MirQasmStatement>(),
            new[] { first, second });

        var error = Assert.Throws<InvalidOperationException>(
            () => MirQasmEmitter.Emit(program));

        Assert.Contains("call cycle", error.Message);
        Assert.Contains("first_final", error.Message);
        Assert.Contains("second_final", error.Message);
    }

    private static MirQasmCallableDefinition FunctionReturningCall(
        MirQasmCallableId id,
        string name,
        MirQasmCallableId callee) =>
        new(
            id,
            name,
            Array.Empty<MirQasmParameter>(),
            Int,
            new MirQasmStatement[]
            {
                new MirQasmReturnStatement(
                    new MirQasmFunctionCallExpression(
                        new MirQasmUserFunctionTarget(callee),
                        Array.Empty<MirQasmExpression>())),
            });

    private static MirOpenQasmTargetProgram CompleteProgram()
    {
        var helperId = new MirQasmCallableId(0);
        var workerId = new MirQasmCallableId(1);
        var callerId = new MirQasmCallableId(2);
        var helperParameter = new MirQasmParameter(
            new MirQasmParameterId(0),
            "source_value",
            Int);
        var helper = new MirQasmCallableDefinition(
            helperId,
            "z_helper",
            new[] { helperParameter },
            Int,
            new MirQasmStatement[]
            {
                new MirQasmReturnStatement(
                    new MirQasmBinaryExpression(
                        MirQasmBinaryOperator.Add,
                        new MirQasmParameterReferenceExpression(
                            helperParameter.Id),
                        new MirQasmLiteralExpression("1"))),
            });

        var workerParameter = new MirQasmParameter(
            new MirQasmParameterId(0),
            "worker_target",
            new MirQasmQubitType());
        var worker = new MirQasmCallableDefinition(
            workerId,
            "a_worker",
            new[] { workerParameter },
            returnType: null,
            new MirQasmStatement[]
            {
                new MirQasmQuantumApplyStatement(
                    new MirQasmBuiltinGateTarget("rx"),
                    new MirQasmExpression[]
                    {
                        new MirQasmBinaryExpression(
                            MirQasmBinaryOperator.Divide,
                            new MirQasmLiteralExpression("pi"),
                            new MirQasmLiteralExpression("2")),
                    },
                    new MirQasmExpression[]
                    {
                        new MirQasmParameterReferenceExpression(
                            workerParameter.Id),
                    }),
            });

        var callerTarget = new MirQasmParameter(
            new MirQasmParameterId(0),
            "caller_target",
            new MirQasmQubitType());
        var callerCount = new MirQasmParameter(
            new MirQasmParameterId(1),
            "caller_count",
            Int);
        var caller = new MirQasmCallableDefinition(
            callerId,
            "m_caller",
            new[] { callerTarget, callerCount },
            returnType: null,
            new MirQasmStatement[]
            {
                new MirQasmValueDeclarationStatement(
                    new MirQasmDeclarationId(0),
                    "next_result",
                    Int,
                    new MirQasmFunctionCallExpression(
                        new MirQasmUserFunctionTarget(helperId),
                        new MirQasmExpression[]
                        {
                            new MirQasmParameterReferenceExpression(
                                callerCount.Id),
                        })),
                new MirQasmQuantumApplyStatement(
                    new MirQasmUserQuantumTarget(workerId),
                    Array.Empty<MirQasmExpression>(),
                    new MirQasmExpression[]
                    {
                        new MirQasmParameterReferenceExpression(
                            callerTarget.Id),
                    }),
                new MirQasmReturnStatement(),
            });

        var q = new MirQasmDeclarationId(0);
        var measured = new MirQasmDeclarationId(1);
        var values = new MirQasmDeclarationId(2);
        var index = new MirQasmDeclarationId(3);
        var body = new MirQasmStatement[]
        {
            new MirQasmQubitDeclarationStatement(
                q,
                "q_final",
                new MirQasmQubitType(2)),
            new MirQasmValueDeclarationStatement(
                measured,
                "measured_final",
                new MirQasmBitType()),
            new MirQasmArrayDeclarationStatement(
                values,
                "values_final",
                new MirQasmArrayType(Int, length: 2),
                new MirQasmExpression[]
                {
                    new MirQasmLiteralExpression("1"),
                    new MirQasmLiteralExpression("2"),
                }),
            new MirQasmValueDeclarationStatement(
                index,
                "index_final",
                Int,
                new MirQasmBinaryExpression(
                    MirQasmBinaryOperator.Add,
                    new MirQasmFunctionCallExpression(
                        new MirQasmUserFunctionTarget(helperId),
                        new MirQasmExpression[]
                        {
                            new MirQasmSizeOfExpression(
                                new MirQasmDeclarationReferenceExpression(
                                    values)),
                        }),
                    new MirQasmUnsignedCastExpression(
                        width: 2,
                        new MirQasmLiteralExpression("\"01\"")))),
            ValueDeclaration(4, "bool_final", MirQasmScalarKind.Bool),
            ValueDeclaration(5, "uint_final", MirQasmScalarKind.UInt),
            ValueDeclaration(6, "float_final", MirQasmScalarKind.Float),
            ValueDeclaration(7, "angle_final", MirQasmScalarKind.Angle),
            new MirQasmValueDeclarationStatement(
                new MirQasmDeclarationId(8),
                "bits_final",
                new MirQasmBitType(3)),
            new MirQasmAssignmentStatement(
                new MirQasmIndexExpression(
                    new MirQasmDeclarationReferenceExpression(values),
                    new MirQasmDeclarationReferenceExpression(index)),
                new MirQasmUnaryExpression(
                    MirQasmUnaryOperator.Negate,
                    new MirQasmDeclarationReferenceExpression(index))),
            new MirQasmMeasurementAssignmentStatement(
                new MirQasmDeclarationReferenceExpression(measured),
                new MirQasmIndexExpression(
                    new MirQasmDeclarationReferenceExpression(q),
                    new MirQasmLiteralExpression("0"))),
            new MirQasmQuantumApplyStatement(
                new MirQasmBuiltinGateTarget("x"),
                Array.Empty<MirQasmExpression>(),
                new MirQasmExpression[]
                {
                    new MirQasmIndexExpression(
                        new MirQasmDeclarationReferenceExpression(q),
                        new MirQasmLiteralExpression("0")),
                    new MirQasmIndexExpression(
                        new MirQasmDeclarationReferenceExpression(q),
                        new MirQasmLiteralExpression("1")),
                },
                new[]
                {
                    MirQasmQuantumModifier.Inverse,
                    MirQasmQuantumModifier.Controlled,
                }),
            new MirQasmIfStatement(
                new MirQasmBinaryExpression(
                    MirQasmBinaryOperator.Equal,
                    new MirQasmDeclarationReferenceExpression(measured),
                    new MirQasmLiteralExpression("1")),
                new MirQasmStatement[]
                {
                    new MirQasmQuantumApplyStatement(
                        new MirQasmUserQuantumTarget(callerId),
                        Array.Empty<MirQasmExpression>(),
                        new MirQasmExpression[]
                        {
                            new MirQasmIndexExpression(
                                new MirQasmDeclarationReferenceExpression(q),
                                new MirQasmLiteralExpression("0")),
                            new MirQasmDeclarationReferenceExpression(index),
                        }),
                },
                new MirQasmStatement[]
                {
                    new MirQasmWhileStatement(
                        new MirQasmBinaryExpression(
                            MirQasmBinaryOperator.Less,
                            new MirQasmDeclarationReferenceExpression(index),
                            new MirQasmLiteralExpression("2")),
                        new MirQasmStatement[]
                        {
                            new MirQasmAssignmentStatement(
                                new MirQasmDeclarationReferenceExpression(index),
                                new MirQasmBinaryExpression(
                                    MirQasmBinaryOperator.Add,
                                    new MirQasmDeclarationReferenceExpression(index),
                                    new MirQasmLiteralExpression("1"))),
                            new MirQasmBreakStatement(),
                        }),
                }),
        };

        return new MirOpenQasmTargetProgram(
            body,
            // Caller deliberately appears first; typed dependencies determine serialization order.
            new[] { caller, helper, worker },
            new[] { "emitted only from the immutable target tree" });
    }

    private static MirQasmValueDeclarationStatement ValueDeclaration(
        int declaration,
        string name,
        MirQasmScalarKind kind) =>
        new(
            new MirQasmDeclarationId(declaration),
            name,
            new MirQasmScalarType(kind));
}
