using System.Text;
using System.Text.RegularExpressions;

namespace Qora.Ir;

/// <summary>
/// Lowers Qora IR (<see cref="QProgram"/>) to OpenQASM 3.0 — the final, text-producing pass, and a pure
/// printer: it invents no names and inverts no bodies. Whole-operation <c>Adjoint</c> on a user op is
/// already gone by now — <see cref="AdjointMaterializer"/> turned each into an ordinary call to a
/// synthesized inverse def (a real op), so this emitter sees only plain defs and plain calls.
///
/// OpenQASM requires declare-before-use for defs and has no forward declarations, so all defs are emitted
/// in dependency (topological) order; on a call cycle — only reachable through forward recursion, which
/// validation (QSEM011) already rejects — it falls back to the stable order.
///
/// The functors that DO reach here are on BUILT-IN gates: <c>Adjoint H</c> → <c>inv @ h</c>,
/// <c>Controlled X</c> → <c>ctrl @ x</c>. A functor left on a user op (which validation forbids — QSEM002
/// for Controlled, and Adjoint is materialized away) is emitted as a visible <c>// Qora:</c> note rather
/// than invalid text, as is a modifier on <c>reset</c> (a statement, not a gate).
/// </summary>
public static class QasmEmitter
{
    private static readonly Regex CountPattern = new(
        @"\b(?<name>[_a-zA-Z][_a-zA-Z0-9]*)\s*\.\s*Count\b", RegexOptions.Compiled);
    private static readonly Regex IndexPattern = new(
        @"\b(?<name>[_a-zA-Z][_a-zA-Z0-9]*)\s*\[\s*(?<index>[_a-zA-Z][_a-zA-Z0-9]*|[0-9]+)\s*\]",
        RegexOptions.Compiled);
    private static readonly Dictionary<string, string> FunctorMods = new()
    {
        ["Adjoint"] = "inv @ ",
        ["Controlled"] = "ctrl @ ",
    };

    /// <summary>Everything statement emission needs to resolve a call site: the set of user-op names
    /// (so a call to one prints as a def call, not a stdgate). Inversion left no state to carry.</summary>
    private sealed record Ctx(HashSet<string> Ops);

    public static string Emit(QProgram? program, IReadOnlyList<string>? notes = null, Passes.SemanticModel? model = null)
    {
        if (program is null || program.Operations.Count == 0) return string.Empty;

        var operations = program.Operations;
        var entry = operations.FirstOrDefault(o => o.Name == "Main") ?? operations[0];
        var subroutines = operations.Where(o => o != entry).ToList();
        var ops = operations.Select(o => o.Name).ToHashSet();

        var opByName = new Dictionary<string, QOperation>();
        foreach (var o in operations) opByName[o.Name] = o;
        var ctx = new Ctx(ops);

        var sb = new StringBuilder();
        // provenance: emitted QASM files travel alone (papers, repos) — record which compiler made them.
        sb.AppendLine($"// generated by Qora v{QoraVersion.Value}");
        // name collisions were auto-resolved by NameMangler; surface each rename here so a reader who sees
        // an adjusted def name knows why (only present when a collision actually occurred).
        if (notes is not null)
            foreach (var note in notes) sb.AppendLine($"// Qora: {note}");
        sb.AppendLine("OPENQASM 3;");
        sb.AppendLine("include \"stdgates.inc\";");

        // Synthesized inverse defs are ordinary ops by this point (AdjointMaterializer), so every def is
        // emitted the same way, in dependency order.
        foreach (var name in OrderDefs(subroutines, entry.Name, opByName, ctx))
        {
            sb.AppendLine();
            EmitDef(opByName[name], ctx, sb, model);
        }

        sb.AppendLine();
        var decls = new StringBuilder();
        HoistDecls(entry.Body, decls);
        var body = new StringBuilder();
        EmitStatements(entry.Body, body, 0, ctx, SeedVarTypes(entry, model));
        sb.Append(decls);
        sb.Append(body);

        return sb.ToString().TrimEnd();
    }

    // --- def ordering (declare-before-use) ---

    /// <summary>
    /// Order all defs so every def appears before its callers: Kahn's algorithm over the call graph,
    /// tie-broken by the stable order (subroutines in source order, then synthesized inverse defs in
    /// discovery order — the order <see cref="AdjointMaterializer"/> appended them). A cycle — possible
    /// only via forward recursion, which OpenQASM cannot express anyway — falls back to appending stably.
    /// </summary>
    private static List<string> OrderDefs(
        List<QOperation> subroutines, string entryName, Dictionary<string, QOperation> opByName, Ctx ctx)
    {
        var nodes = subroutines.Select(s => s.Name).ToList();
        var index = new Dictionary<string, int>();
        for (int i = 0; i < nodes.Count; i++) index[nodes[i]] = i;

        // edges: callee -> callers (a def depends on the defs it calls)
        var dependents = new Dictionary<int, List<int>>();
        var indegree = new int[nodes.Count];
        for (int i = 0; i < nodes.Count; i++)
        {
            var deps = new HashSet<string>();
            CollectCallDeps(opByName[nodes[i]].Body, entryName, ctx, deps);
            foreach (var dep in deps)
            {
                if (!index.TryGetValue(dep, out var j) || j == i) continue;
                if (!dependents.TryGetValue(j, out var list)) dependents[j] = list = new List<int>();
                list.Add(i);
                indegree[i]++;
            }
        }

        var result = new List<string>();
        var emitted = new bool[nodes.Count];
        while (result.Count < nodes.Count)
        {
            var next = -1;
            for (int i = 0; i < nodes.Count; i++)
                if (!emitted[i] && indegree[i] == 0) { next = i; break; }
            if (next < 0) // cycle: emit the stably-first remaining node anyway
                for (int i = 0; i < nodes.Count; i++)
                    if (!emitted[i]) { next = i; break; }

            emitted[next] = true;
            result.Add(nodes[next]);
            if (dependents.TryGetValue(next, out var users))
                foreach (var u in users) indegree[u]--;
        }
        return result;
    }

    /// <summary>Collect which defs a body's call sites reference: every plain call to a user op (functors
    /// on a user op never reach here — Adjoint is materialized away, Controlled is a validation error).</summary>
    private static void CollectCallDeps(IReadOnlyList<QStmt> stmts, string entryName, Ctx ctx, HashSet<string> into)
    {
        foreach (var stmt in stmts)
        {
            switch (stmt)
            {
                case QGate g when ctx.Ops.Contains(g.Name) && g.Name != entryName && g.Functors.Count == 0:
                    into.Add(g.Name);
                    break;
                case QIf i:
                    CollectCallDeps(i.Then, entryName, ctx, into);
                    CollectCallDeps(i.Else, entryName, ctx, into);
                    break;
                case QFor f:
                    CollectCallDeps(f.Body, entryName, ctx, into);
                    break;
                case QWhile w:
                    CollectCallDeps(w.Body, entryName, ctx, into);
                    break;
                case QRepeat r:
                    CollectCallDeps(r.Body, entryName, ctx, into);
                    break;
                case QConjugate c:
                    CollectCallDeps(c.Within, entryName, ctx, into);
                    CollectCallDeps(c.Apply, entryName, ctx, into);
                    break;
            }
        }
    }

    // --- def emission ---

    private static void EmitDef(QOperation op, Ctx ctx, StringBuilder sb, Passes.SemanticModel? model)
    {
        var ps = string.Join(", ", op.Params.Select(EmitParam));
        var decls = new StringBuilder();
        HoistDecls(op.Body, decls);
        var body = new StringBuilder();
        EmitStatements(op.Body, body, 1, ctx, SeedVarTypes(op, model));

        sb.AppendLine($"def {op.Name}({ps}) {{");
        foreach (var line in decls.ToString().Split('\n'))
            if (line.Trim().Length > 0) sb.AppendLine($"  {line.TrimEnd()}");
        sb.Append(body);
        sb.AppendLine("}");
    }

    private static void HoistDecls(IReadOnlyList<QStmt> stmts, StringBuilder decls) =>
        HoistDecls(stmts, decls, new HashSet<string>());

    // Qubit registers AND measure bits are hoisted to the top of the def body. Registers because `use` is
    // entry-top-level only (QSEM012); measure bits because OpenQASM importers (e.g. Qiskit) accept only
    // GLOBAL classical declarations, not local ones inside a control-flow block — so a measure written deep
    // in an `if`/`for`/`repeat` emits its `bit r;` here at the top and just an `r = measure …;` assignment
    // in place (see EmitDecl). This is purely an EMISSION shape: the source language keeps measure bits
    // block-scoped (a use outside the declaring block is QSEM025). Hoisted names are deduplicated by name —
    // the same measure bit declared in both branches of an if/else must become ONE top-level `bit r;`
    // (QASM's top scope is flat). The symbol table guarantees no two hoisted names (register/param/measure
    // bit) collide across enclosing scopes, so the flattening here is always sound.
    private static void HoistDecls(IReadOnlyList<QStmt> stmts, StringBuilder decls, HashSet<string> seen)
    {
        foreach (var stmt in stmts)
        {
            switch (stmt)
            {
                case QUse u:
                    if (seen.Add(u.Name)) decls.AppendLine($"qubit[{u.Size}] {u.Name};");
                    break;
                case QDecl d when d.Value is QMeasure:
                    if (seen.Add(d.Name)) decls.AppendLine($"{TypeName(d.Type) ?? "bit"} {d.Name};");
                    break;
                case QIf i:
                    HoistDecls(i.Then, decls, seen);
                    HoistDecls(i.Else, decls, seen);
                    break;
                case QFor f:
                    HoistDecls(f.Body, decls, seen);
                    break;
                case QWhile w:
                    HoistDecls(w.Body, decls, seen);
                    break;
                case QRepeat r:
                    HoistDecls(r.Body, decls, seen);
                    break;
                case QConjugate c:
                    // Defensive only — ConjugationLowering removes every QConjugate before emission. If one
                    // somehow survived, still hoist any declarations nested inside it rather than losing them
                    // (ReferentialCheck raises the QINTERNAL that actually blocks this output). NOT a blanket
                    // `default:` — this switch deliberately lets gates/assigns/classical decls fall through.
                    HoistDecls(c.Within, decls, seen);
                    HoistDecls(c.Apply, decls, seen);
                    break;
            }
        }
    }

    private static void EmitStatements(IReadOnlyList<QStmt> stmts, StringBuilder body, int indent, Ctx ctx, Dictionary<string, string> varTypes)
    {
        var pad = new string(' ', indent * 2);

        foreach (var stmt in stmts)
        {
            switch (stmt)
            {
                case QUse:
                    break; // hoisted

                case QGate g:
                    body.AppendLine(pad + EmitStmtInline(g, ctx));
                    break;

                case QDecl d:
                    EmitDecl(d, body, pad, varTypes);
                    break;

                case QAssign a:
                    var target = a.Index is null ? a.Name : $"{a.Name}[{RenderText(a.Index)}]";
                    body.AppendLine($"{pad}{target} = {RenderExpr(a.Value)};");
                    break;

                case QIf i:
                    EmitIf(i, body, indent, ctx, varTypes);
                    break;

                case QFor f:
                    var range = f.Step is null
                        ? $"[{RenderText(f.From)}:{RenderText(f.To)}]"
                        : $"[{RenderText(f.From)}:{RenderText(f.Step)}:{RenderText(f.To)}]";
                    body.AppendLine($"{pad}for int {f.Var} in {range} {{");
                    EmitStatements(f.Body, body, indent + 1, ctx, varTypes);
                    body.AppendLine($"{pad}}}");
                    break;

                case QWhile w:
                    body.AppendLine($"{pad}while ({RenderText(RewriteBitCond(w.Cond.Text, varTypes))}) {{");
                    EmitStatements(w.Body, body, indent + 1, ctx, varTypes);
                    body.AppendLine($"{pad}}}");
                    break;

                case QRepeat r:
                    body.AppendLine($"{pad}while (true) {{");
                    EmitStatements(r.Body, body, indent + 1, ctx, varTypes);
                    body.AppendLine($"{pad}  if ({RenderText(RewriteBitCond(r.Until.Text, varTypes))}) {{ break; }}");
                    body.AppendLine($"{pad}}}");
                    break;

                default:
                    // Defense in depth: every real QStmt has a case above, and an un-flattened QConjugate is
                    // already turned into a QINTERNAL error by ReferentialCheck (which gates this emission),
                    // so this is unreachable in a successful compile. Still, emit a VISIBLE marker rather than
                    // silently dropping a statement — a silent drop was the original latent bug.
                    body.AppendLine($"{pad}// Qora: internal error — unhandled {stmt.GetType().Name} reached the emitter");
                    break;
            }
        }
    }

    private static void EmitIf(QIf node, StringBuilder body, int indent, Ctx ctx, Dictionary<string, string> varTypes)
    {
        var pad = new string(' ', indent * 2);

        body.AppendLine($"{pad}if ({RenderText(RewriteBitCond(node.Cond.Text, varTypes))}) {{");
        EmitStatements(node.Then, body, indent + 1, ctx, varTypes);
        body.AppendLine($"{pad}}}");

        if (node.Else.Count > 0)
        {
            body.AppendLine($"{pad}else {{");
            EmitStatements(node.Else, body, indent + 1, ctx, varTypes);
            body.AppendLine($"{pad}}}");
        }
    }

    /// <summary>Render one gate/call/functor invocation as a single line (used inline and inside adj defs).</summary>
    private static string EmitStmtInline(QStmt stmt, Ctx ctx)
    {
        if (stmt is not QGate gate) return string.Empty;

        var name = gate.Name;
        var isUserOp = ctx.Ops.Contains(name);
        var args = gate.Args.Select(RenderArg).ToList();
        var modifier = string.Concat(gate.Functors.Select(f => FunctorMods.TryGetValue(f, out var m) ? m : string.Empty));

        // A functor on a user op has no lowering (OpenQASM modifiers apply to gates, not defs) and does
        // not occur in validated, materialized IR — whole-op Adjoint became a plain inverse-def call and
        // Controlled on a user op is QSEM002. Kept as a visible note in case an unvalidated path reaches here.
        if (isUserOp && gate.Functors.Count > 0)
            return $"// Qora: {gate.Functors[0]} of `{name}` has no OpenQASM lowering (a modifier cannot apply to a def)";

        // reset is a statement, not a gate — it takes no modifiers.
        if (gate.Functors.Count > 0 && MapGate(name) == "reset")
            return $"// Qora: {string.Join(" ", gate.Functors)} {name} is not supported (reset is not a gate and takes no modifiers)";

        if (QoraGates.Rotations.Contains(name) && args.Count >= 2)
            return $"{modifier}{MapGate(name)}({args[0]}) {string.Join(", ", args.Skip(1))};";

        return isUserOp
            ? $"{modifier}{name}({string.Join(", ", args)});"
            : $"{modifier}{MapGate(name)} {string.Join(", ", args)};";
    }

    private static void EmitDecl(QDecl d, StringBuilder body, string pad, Dictionary<string, string> varTypes)
    {
        if (d.IsArray)
        {
            var elementType = TypeName(d.Type) ?? throw new InvalidOperationException(
                $"QINTERNAL: array `{d.Name}` reached emission without an element type");
            var length = d.Value switch
            {
                QArrayLiteral literal => literal.Elements.Count,
                QArrayNew allocation => allocation.Length,
                _ => throw new InvalidOperationException(
                    $"QINTERNAL: array `{d.Name}` reached emission without an array initializer"),
            };
            // varTypes drives RewriteBitCond (`if (f[1] == true)`), so it is recorded for BOTH shapes below.
            varTypes.TryAdd(d.Name, elementType);

            // `bit` is the one element type that cannot take the general form: "bit, bit[n] and stretch are
            // not valid array base types" (OpenQASM 3, types.rst). Bits get the dedicated register type.
            if (d.Type == QType.Bit)
            {
                EmitBitRegisterDecl(d, length, body, pad);
                return;
            }

            var initializer = d.Value switch
            {
                QArrayLiteral literal => string.Join(", ", literal.Elements.Select(RenderExpr)),
                QArrayNew allocation => string.Join(", ", Enumerable.Repeat(DefaultValue(allocation.ElementType), allocation.Length)),
                _ => string.Empty,
            };
            body.AppendLine($"{pad}array[{elementType}, {length}] {d.Name} = {{{initializer}}};");
            return;
        }

        if (d.Value is QMeasure)
        {
            // The `bit r;` declaration is hoisted to the top of the def body (HoistDecls) for OpenQASM
            // importer compatibility; here we emit only the assignment, in place. Source-level block scoping
            // is enforced separately by the symbol table (out-of-block use = QSEM025).
            body.AppendLine($"{pad}{d.Name} = {RenderExpr(d.Value)};");
            return;
        }

        var type = TypeName(d.Type) ?? InferDefaultType(d.Value, varTypes);
        varTypes.TryAdd(d.Name, type);
        var prefix = d.IsConst ? "const " : string.Empty;
        body.AppendLine($"{pad}{prefix}{type} {d.Name} = {RenderExpr(d.Value)};");
    }

    /// <summary>
    /// A <c>bit[]</c> declaration, as OpenQASM's dedicated <c>bit[N]</c> register.
    /// <para><c>new bit[N]</c> emits the all-zeros bitstring rather than a bare <c>bit[N] f;</c>, because a
    /// bare register is UNDEFINED, not zeroed, and Qora's <c>new T[N]</c> promises zero-initialization for
    /// every other element type. An all-zeros string is the same read either way, so the ordering caveat
    /// below cannot bite it.</para>
    /// <para>An array LITERAL is written element by element and never as a bitstring: the spec's prose puts
    /// element 0 at the RIGHT (least-significant) end while Braket reads it at the LEFT, so any non-uniform
    /// bitstring would silently reverse the array. Indexed writes mean the same thing on both.</para>
    /// </summary>
    private static void EmitBitRegisterDecl(QDecl d, int length, StringBuilder body, string pad)
    {
        if (d.Value is QArrayNew)
        {
            body.AppendLine($"{pad}bit[{length}] {d.Name} = \"{new string('0', length)}\";");
            return;
        }

        var literal = (QArrayLiteral)d.Value!;
        body.AppendLine($"{pad}bit[{length}] {d.Name};");
        for (var i = 0; i < literal.Elements.Count; i++)
            body.AppendLine($"{pad}{d.Name}[{i}] = {RenderExpr(literal.Elements[i])};");
    }

    private static string DefaultValue(QType type) => type switch
    {
        QType.Float or QType.Angle => "0.0",
        _ => "0",
    };

    /// <summary>
    /// The emitted type of an untyped `var`/`const`, inferred from its initializer using the type map (which
    /// the symbol table seeds, so a referenced name's type — including a bit — is known):
    /// <list type="bullet">
    ///   <item><b>float</b> — a real-valued initializer: a float literal, a built-in constant, or a name
    ///         already known float/angle (so floatness propagates: `var a = pi; var b = a / 2;`). `int t = pi
    ///         / 4;` would be an invalid narrowing.</item>
    ///   <item><b>bit</b> — a lone bit reference (`var x = r;` where `r` is a bit); emitting `int x = r;`
    ///         would be a wrong-typed (bit→int) declaration.</item>
    ///   <item><b>int</b> — everything else (the default).</item>
    /// </list>
    /// </summary>
    private static string InferDefaultType(QExpr value, Dictionary<string, string> varTypes)
    {
        if (value is not QText t) return "int";
        var tokens = t.Text.Split(' ');
        if (tokens.Any(tok => tok is "pi" or "tau" or "euler" || tok.Contains('.')
                              || (varTypes.TryGetValue(tok, out var vt) && vt is "float" or "angle")))
            return "float";
        if (tokens.Length == 1 && varTypes.TryGetValue(tokens[0], out var t0) && t0 == "bit")
            return "bit";
        return "int";
    }

    /// <summary>
    /// The per-op map of every classical name to its emitted type. It is derived from the ONE source of
    /// name→type — the symbol table — rather than re-scanned by hand, so NO declaration kind can be missed:
    /// parameters, <c>use</c> registers, vars, consts, measure bits AND loop variables all carry their type
    /// there (a hand-rolled scan previously forgot loop variables, so `!i` emitted an invalid `! ( i )`).
    /// Qubits and untyped <c>var</c>s are absent — a qubit is never a classical value, and an untyped var's
    /// type is inferred at its declaration by <see cref="InferDefaultType"/> and added then. It is a flat
    /// whole-op superset, so bit-typed rendering (`r == 1` → `r == true`) and the classical `!x` → `x == 0`
    /// rewrite are consistent wherever the name resolves; block scoping guarantees no use before declaration.
    ///
    /// With a <see cref="Passes.SemanticModel"/> the map is READ, not rebuilt: each declaring node's CURRENT
    /// (post-mangling) name is paired with its validation-time type through the node's stable Id — the exact
    /// current-name ↔ proven-type join a rebuild cannot express (a rebuild sees mangled names only). The
    /// walk mirrors the scope tree's <see cref="Passes.Scope.AllSymbols"/> order (this level's declarations,
    /// then nested blocks in program order) so shadowed names resolve to the same final entry either way.
    /// Without a model (standalone <see cref="Emit"/> call), the old full rebuild remains as the fallback.
    /// </summary>
    private static Dictionary<string, string> SeedVarTypes(QOperation op, Passes.SemanticModel? model)
    {
        if (model is not null && model.FindRootScope(op.Id) is not null)
        {
            var map = new Dictionary<string, string>();
            var complete = true;
            void AddNamed(string currentName, int nodeId)
            {
                var sym = model.FindSymbol(nodeId);
                if (sym is null) { complete = false; return; }
                if (TypeName(sym.Type) is { } t) map[currentName] = t;
            }
            void Level(IReadOnlyList<QStmt> stmts)
            {
                foreach (var s in stmts) if (s is QDecl d) AddNamed(d.Name, d.Id);
                foreach (var s in stmts)
                    switch (s)
                    {
                        case QFor f: AddNamed(f.Var, f.Id); Level(f.Body); break;
                        case QIf i: Level(i.Then); Level(i.Else); break;
                        case QWhile w: Level(w.Body); break;
                        case QRepeat r: Level(r.Body); break;
                        case QConjugate c: Level(c.Within); Level(c.Apply); break;
                    }
            }
            foreach (var p in op.Params) AddNamed(p.Name, p.Id);
            Level(op.Body);
            if (complete) return map;
            // a node the model has never seen (no Id hit, no derivation chain) — fall through to a rebuild
            // rather than emit from a partial map.
        }

        var sink = new List<QoraError>();                 // types only — any diagnostics are the validator's job
        var root = Passes.SymbolTableBuilder.Build(op, sink);
        var rebuilt = new Dictionary<string, string>();
        foreach (var s in root.AllSymbols())
            if (TypeName(s.Type) is { } t) rebuilt[s.SourceName] = t;   // Int/Bit/Float/Angle; Qubit and untyped → null → skipped; the rebuild ran over the CURRENT tree, so its "source" IS the mangled program
        return rebuilt;
    }

    /// <summary>
    /// Bit comparisons emit against BOOL literals: `r == 1` → `r == true`, `r != 0` → `r != false`
    /// (either operand order) whenever the name is a known bit. Both spellings are valid OpenQASM 3,
    /// but the dominant consumer (Qiskit's qasm3 importer) accepts only `bit == const bool` — so emit
    /// the one that actually loads. Ints and unknown names are left untouched.
    /// </summary>
    private static string RewriteBitCond(string text, Dictionary<string, string> varTypes)
    {
        // Compact indexed references first so `flags [ i ]` is one token and can inherit the array's
        // element type during the same bit-condition rewrite used for scalar bits.
        text = RenderText(text);
        var toks = text.Split(' ');

        // OpenQASM has no logical `!` on a classical scalar (it reads a bit/int/float as a numeric
        // literal, not a bool): rewrite a negated classical value `! ( x )` to `x == 0` (a bit then
        // becomes `x == false` via the loop below). Qora source keeps `!x`; only the emitted QASM changes
        // — the same emit-time adjustment as `s == 1` -> `s == true`.
        var neg = new List<string>(toks.Length);
        for (var i = 0; i < toks.Length; i++)
            if (toks[i] == "!" && i + 3 < toks.Length && toks[i + 1] == "(" && TypeOf(toks[i + 2]) is not null && toks[i + 3] == ")")
            {
                neg.Add(toks[i + 2]); neg.Add("=="); neg.Add("0");
                i += 3;
            }
            else neg.Add(toks[i]);
        toks = neg.ToArray();

        for (var i = 0; i + 2 < toks.Length; i++)
        {
            if (toks[i + 1] is not ("==" or "!=")) continue;
            if (IsBit(toks[i]) && toks[i + 2] is "0" or "1") toks[i + 2] = toks[i + 2] == "1" ? "true" : "false";
            else if (IsBit(toks[i + 2]) && toks[i] is "0" or "1") toks[i] = toks[i] == "1" ? "true" : "false";
        }
        return string.Join(" ", toks);

        bool IsBit(string tok) => TypeOf(tok) == "bit";

        string? TypeOf(string token)
        {
            if (varTypes.TryGetValue(token, out var direct)) return direct;
            var indexed = IndexPattern.Match(token);
            return indexed.Success && indexed.Index == 0 && indexed.Length == token.Length
                && varTypes.TryGetValue(indexed.Groups["name"].Value, out var elementType)
                    ? elementType
                    : null;
        }
    }

    private static string EmitParam(QParam p) => p.Type switch
    {
        _ when p.Type != QType.Qubit && p.IsArray => $"mutable array[{TypeName(p.Type)}, #dim = 1] {p.Name}",
        QType.Int => $"int {p.Name}",
        QType.Bit => $"bit {p.Name}",
        QType.Float => $"float {p.Name}",
        QType.Angle => $"angle {p.Name}",
        QType.Qubit when p.RegisterSize is int n => $"qubit[{n}] {p.Name}",
        QType.Qubit when p.IsQubitArray => throw new InvalidOperationException(
            $"QINTERNAL: unspecialized Qubit[] parameter `{p.Name}` reached OpenQASM emission"),
        _ => $"qubit {p.Name}",
    };

    private static string RenderArg(QArg arg) => arg switch
    {
        QQubitArg q => $"{q.Reg}[{q.Index}]",
        QTextArg t => RenderText(t.Text),
        _ => string.Empty,
    };

    private static string RenderExpr(QExpr expr) => expr switch
    {
        QMeasure m => m.Target is null ? "measure" : $"measure {m.Target.Reg}[{m.Target.Index}]",
        QText t => RenderText(t.Text),
        QArrayLiteral literal => $"{{{string.Join(", ", literal.Elements.Select(RenderExpr))}}}",
        QArrayNew allocation => $"{{{string.Join(", ", Enumerable.Repeat(DefaultValue(allocation.ElementType), allocation.Length))}}}",
        _ => string.Empty,
    };

    private static string RenderText(string text)
    {
        var rendered = CountPattern.Replace(text, match => $"sizeof({match.Groups["name"].Value})");
        rendered = IndexPattern.Replace(rendered,
            match => $"{match.Groups["name"].Value}[{match.Groups["index"].Value}]");
        return rendered;
    }

    private static string MapGate(string name) =>
        QoraGates.Names.TryGetValue(name, out var qasm) ? qasm : name.ToLowerInvariant();

    private static string? TypeName(QType? t) => t switch { QType.Int => "int", QType.Bit => "bit", QType.Float => "float", QType.Angle => "angle", _ => null };
}
