using System.Text;

namespace Qora.Ir;

/// <summary>
/// Lowers Qora IR (<see cref="QProgram"/>) to OpenQASM 3.0 — the final, text-producing pass, and a pure
/// printer: it invents no names and inverts no bodies. Whole-operation <c>Adjoint</c> on a user op is
/// already gone by now — <see cref="AdjointMaterializer"/> turned each into an ordinary call to a
/// synthesized inverse def (a real op), so this emitter sees only plain defs and plain calls.
///
/// OpenQASM requires declare-before-use for defs and has no forward declarations, so all defs are emitted
/// in dependency (topological) order; on a call cycle — only reachable through forward recursion, which
/// validation (QSEM011) already rejects — it falls back to the stable order.
///
/// The functors that DO reach here are on BUILT-IN gates: <c>Adjoint H</c> → <c>inv @ h</c>,
/// <c>Controlled X</c> → <c>ctrl @ x</c>. A functor left on a user op (which validation forbids — QSEM002
/// for Controlled, and Adjoint is materialized away) is emitted as a visible <c>// Qora:</c> note rather
/// than invalid text, as is a modifier on <c>reset</c> (a statement, not a gate).
/// </summary>
public static class QasmEmitter
{
    private static readonly Dictionary<string, string> FunctorMods = new()
    {
        ["Adjoint"] = "inv @ ",
        ["Controlled"] = "ctrl @ ",
    };

    /// <summary>Everything statement emission needs to resolve a call site: the set of user-op names
    /// (so a call to one prints as a def call, not a stdgate). Inversion left no state to carry.</summary>
    private sealed record Ctx(HashSet<string> Ops);

    public static string Emit(QProgram? program, IReadOnlyList<string>? notes = null)
    {
        if (program is null || program.Operations.Count == 0) return string.Empty;

        var operations = program.Operations;
        var entry = operations.FirstOrDefault(o => o.Name == "Main") ?? operations[0];
        var subroutines = operations.Where(o => o != entry).ToList();
        var ops = operations.Select(o => o.Name).ToHashSet();

        var opByName = new Dictionary<string, QOperation>();
        foreach (var o in operations) opByName[o.Name] = o;
        var ctx = new Ctx(ops);

        var sb = new StringBuilder();
        // provenance: emitted QASM files travel alone (papers, repos) — record which compiler made them.
        sb.AppendLine($"// generated by Qora v{QoraVersion.Value}");
        // name collisions were auto-resolved by NameMangler; surface each rename here so a reader who sees
        // an adjusted def name knows why (only present when a collision actually occurred).
        if (notes is not null)
            foreach (var note in notes) sb.AppendLine($"// Qora: {note}");
        sb.AppendLine("OPENQASM 3;");
        sb.AppendLine("include \"stdgates.inc\";");

        // Synthesized inverse defs are ordinary ops by this point (AdjointMaterializer), so every def is
        // emitted the same way, in dependency order.
        foreach (var name in OrderDefs(subroutines, entry.Name, opByName, ctx))
        {
            sb.AppendLine();
            EmitDef(opByName[name], ctx, sb);
        }

        sb.AppendLine();
        var decls = new StringBuilder();
        HoistDecls(entry.Body, decls);
        var body = new StringBuilder();
        EmitStatements(entry.Body, body, 0, ctx, SeedVarTypes(entry));
        sb.Append(decls);
        sb.Append(body);

        return sb.ToString().TrimEnd();
    }

    // --- def ordering (declare-before-use) ---

    /// <summary>
    /// Order all defs so every def appears before its callers: Kahn's algorithm over the call graph,
    /// tie-broken by the stable order (subroutines in source order, then synthesized inverse defs in
    /// discovery order — the order <see cref="AdjointMaterializer"/> appended them). A cycle — possible
    /// only via forward recursion, which OpenQASM cannot express anyway — falls back to appending stably.
    /// </summary>
    private static List<string> OrderDefs(
        List<QOperation> subroutines, string entryName, Dictionary<string, QOperation> opByName, Ctx ctx)
    {
        var nodes = subroutines.Select(s => s.Name).ToList();
        var index = new Dictionary<string, int>();
        for (int i = 0; i < nodes.Count; i++) index[nodes[i]] = i;

        // edges: callee -> callers (a def depends on the defs it calls)
        var dependents = new Dictionary<int, List<int>>();
        var indegree = new int[nodes.Count];
        for (int i = 0; i < nodes.Count; i++)
        {
            var deps = new HashSet<string>();
            CollectCallDeps(opByName[nodes[i]].Body, entryName, ctx, deps);
            foreach (var dep in deps)
            {
                if (!index.TryGetValue(dep, out var j) || j == i) continue;
                if (!dependents.TryGetValue(j, out var list)) dependents[j] = list = new List<int>();
                list.Add(i);
                indegree[i]++;
            }
        }

        var result = new List<string>();
        var emitted = new bool[nodes.Count];
        while (result.Count < nodes.Count)
        {
            var next = -1;
            for (int i = 0; i < nodes.Count; i++)
                if (!emitted[i] && indegree[i] == 0) { next = i; break; }
            if (next < 0) // cycle: emit the stably-first remaining node anyway
                for (int i = 0; i < nodes.Count; i++)
                    if (!emitted[i]) { next = i; break; }

            emitted[next] = true;
            result.Add(nodes[next]);
            if (dependents.TryGetValue(next, out var users))
                foreach (var u in users) indegree[u]--;
        }
        return result;
    }

    /// <summary>Collect which defs a body's call sites reference: every plain call to a user op (functors
    /// on a user op never reach here — Adjoint is materialized away, Controlled is a validation error).</summary>
    private static void CollectCallDeps(IReadOnlyList<QStmt> stmts, string entryName, Ctx ctx, HashSet<string> into)
    {
        foreach (var stmt in stmts)
        {
            switch (stmt)
            {
                case QGate g when ctx.Ops.Contains(g.Name) && g.Name != entryName && g.Functors.Count == 0:
                    into.Add(g.Name);
                    break;
                case QIf i:
                    CollectCallDeps(i.Then, entryName, ctx, into);
                    CollectCallDeps(i.Else, entryName, ctx, into);
                    break;
                case QFor f:
                    CollectCallDeps(f.Body, entryName, ctx, into);
                    break;
                case QWhile w:
                    CollectCallDeps(w.Body, entryName, ctx, into);
                    break;
                case QRepeat r:
                    CollectCallDeps(r.Body, entryName, ctx, into);
                    break;
                case QConjugate c:
                    CollectCallDeps(c.Within, entryName, ctx, into);
                    CollectCallDeps(c.Apply, entryName, ctx, into);
                    break;
            }
        }
    }

    // --- def emission ---

    private static void EmitDef(QOperation op, Ctx ctx, StringBuilder sb)
    {
        var ps = string.Join(", ", op.Params.Select(EmitParam));
        var decls = new StringBuilder();
        HoistDecls(op.Body, decls);
        var body = new StringBuilder();
        EmitStatements(op.Body, body, 1, ctx, SeedVarTypes(op));

        sb.AppendLine($"def {op.Name}({ps}) {{");
        foreach (var line in decls.ToString().Split('\n'))
            if (line.Trim().Length > 0) sb.AppendLine($"  {line.TrimEnd()}");
        sb.Append(body);
        sb.AppendLine("}");
    }

    private static void HoistDecls(IReadOnlyList<QStmt> stmts, StringBuilder decls) =>
        HoistDecls(stmts, decls, new HashSet<string>());

    // Hoisted declarations are deduplicated by name: the same measure-bit declared in both branches of
    // an if/else must become ONE top-level declaration (QASM scopes are flat; a duplicate is invalid).
    private static void HoistDecls(IReadOnlyList<QStmt> stmts, StringBuilder decls, HashSet<string> seen)
    {
        foreach (var stmt in stmts)
        {
            switch (stmt)
            {
                case QUse u:
                    if (seen.Add(u.Name)) decls.AppendLine($"qubit[{u.Size}] {u.Name};");
                    break;
                case QDecl d when d.Value is QMeasure:
                    if (seen.Add(d.Name)) decls.AppendLine($"{TypeName(d.Type) ?? "bit"} {d.Name};");
                    break;
                case QIf i:
                    HoistDecls(i.Then, decls, seen);
                    HoistDecls(i.Else, decls, seen);
                    break;
                case QFor f:
                    HoistDecls(f.Body, decls, seen);
                    break;
                case QWhile w:
                    HoistDecls(w.Body, decls, seen);
                    break;
                case QRepeat r:
                    HoistDecls(r.Body, decls, seen);
                    break;
            }
        }
    }

    private static void EmitStatements(IReadOnlyList<QStmt> stmts, StringBuilder body, int indent, Ctx ctx, Dictionary<string, string> varTypes)
    {
        var pad = new string(' ', indent * 2);

        foreach (var stmt in stmts)
        {
            switch (stmt)
            {
                case QUse:
                    break; // hoisted

                case QGate g:
                    body.AppendLine(pad + EmitStmtInline(g, ctx));
                    break;

                case QDecl d:
                    EmitDecl(d, body, pad, varTypes);
                    break;

                case QAssign a:
                    body.AppendLine($"{pad}{a.Name} = {RenderExpr(a.Value)};");
                    break;

                case QIf i:
                    EmitIf(i, body, indent, ctx, varTypes);
                    break;

                case QFor f:
                    var range = f.Step is null ? $"[{f.From}:{f.To}]" : $"[{f.From}:{f.Step}:{f.To}]";
                    body.AppendLine($"{pad}for int {f.Var} in {range} {{");
                    EmitStatements(f.Body, body, indent + 1, ctx, varTypes);
                    body.AppendLine($"{pad}}}");
                    break;

                case QWhile w:
                    body.AppendLine($"{pad}while ({RewriteBitCond(w.Cond.Text, varTypes)}) {{");
                    EmitStatements(w.Body, body, indent + 1, ctx, varTypes);
                    body.AppendLine($"{pad}}}");
                    break;

                case QRepeat r:
                    body.AppendLine($"{pad}while (true) {{");
                    EmitStatements(r.Body, body, indent + 1, ctx, varTypes);
                    body.AppendLine($"{pad}  if ({RewriteBitCond(r.Until.Text, varTypes)}) {{ break; }}");
                    body.AppendLine($"{pad}}}");
                    break;
            }
        }
    }

    private static void EmitIf(QIf node, StringBuilder body, int indent, Ctx ctx, Dictionary<string, string> varTypes)
    {
        var pad = new string(' ', indent * 2);

        body.AppendLine($"{pad}if ({RewriteBitCond(node.Cond.Text, varTypes)}) {{");
        EmitStatements(node.Then, body, indent + 1, ctx, varTypes);
        body.AppendLine($"{pad}}}");

        if (node.Else.Count > 0)
        {
            body.AppendLine($"{pad}else {{");
            EmitStatements(node.Else, body, indent + 1, ctx, varTypes);
            body.AppendLine($"{pad}}}");
        }
    }

    /// <summary>Render one gate/call/functor invocation as a single line (used inline and inside adj defs).</summary>
    private static string EmitStmtInline(QStmt stmt, Ctx ctx)
    {
        if (stmt is not QGate gate) return string.Empty;

        var name = gate.Name;
        var isUserOp = ctx.Ops.Contains(name);
        var args = gate.Args.Select(RenderArg).ToList();
        var modifier = string.Concat(gate.Functors.Select(f => FunctorMods.TryGetValue(f, out var m) ? m : string.Empty));

        // A functor on a user op has no lowering (OpenQASM modifiers apply to gates, not defs) and does
        // not occur in validated, materialized IR — whole-op Adjoint became a plain inverse-def call and
        // Controlled on a user op is QSEM002. Kept as a visible note in case an unvalidated path reaches here.
        if (isUserOp && gate.Functors.Count > 0)
            return $"// Qora: {gate.Functors[0]} of `{name}` has no OpenQASM lowering (a modifier cannot apply to a def)";

        // reset is a statement, not a gate — it takes no modifiers.
        if (gate.Functors.Count > 0 && MapGate(name) == "reset")
            return $"// Qora: {string.Join(" ", gate.Functors)} {name} is not supported (reset is not a gate and takes no modifiers)";

        if (QoraGates.Rotations.Contains(name) && args.Count >= 2)
            return $"{modifier}{MapGate(name)}({args[0]}) {string.Join(", ", args.Skip(1))};";

        return isUserOp
            ? $"{modifier}{name}({string.Join(", ", args)});"
            : $"{modifier}{MapGate(name)} {string.Join(", ", args)};";
    }

    private static void EmitDecl(QDecl d, StringBuilder body, string pad, Dictionary<string, string> varTypes)
    {
        if (d.Value is QMeasure)
        {
            body.AppendLine($"{pad}{d.Name} = {RenderExpr(d.Value)};");
            return;
        }

        var type = TypeName(d.Type) ?? InferDefaultType(d.Value, varTypes);
        varTypes.TryAdd(d.Name, type);
        var prefix = d.IsConst ? "const " : string.Empty;
        body.AppendLine($"{pad}{prefix}{type} {d.Name} = {RenderExpr(d.Value)};");
    }

    /// <summary>
    /// The default type of an untyped `var`/`const`: `float` when the initializer is real-valued — a
    /// float literal, a built-in constant, or a variable already known to be float (so floatness
    /// propagates: `var a = pi; var b = a / 2;` makes `b` a float too). `int t = pi / 4;` would be an
    /// invalid narrowing in the emitted QASM.
    /// </summary>
    private static string InferDefaultType(QExpr value, Dictionary<string, string> varTypes) =>
        value is QText t && t.Text.Split(' ').Any(tok =>
            tok is "pi" or "tau" or "euler" || tok.Contains('.')
            || (varTypes.TryGetValue(tok, out var vt) && (vt == "float" || vt == "angle")))
            ? "float" : "int";

    /// <summary>
    /// Seed the per-op variable-type map: classical parameters, plus every measure-bit / bit-typed
    /// declaration anywhere in the body (pre-scanned so a condition emitted before its declaration
    /// line still knows the name is a bit — declarations are hoisted anyway).
    /// </summary>
    private static Dictionary<string, string> SeedVarTypes(QOperation op)
    {
        var map = new Dictionary<string, string>();
        foreach (var p in op.Params)
            if (p.Type == QType.Int) map[p.Name] = "int";
            else if (p.Type == QType.Bit) map[p.Name] = "bit";
            else if (p.Type == QType.Float) map[p.Name] = "float";
            else if (p.Type == QType.Angle) map[p.Name] = "angle";

        void Scan(IReadOnlyList<QStmt> stmts)
        {
            foreach (var s in stmts)
                switch (s)
                {
                    case QDecl d when d.Value is QMeasure || d.Type == QType.Bit: map.TryAdd(d.Name, "bit"); break;
                    case QIf i: Scan(i.Then); Scan(i.Else); break;
                    case QFor f: Scan(f.Body); break;
                    case QWhile w: Scan(w.Body); break;
                    case QRepeat r: Scan(r.Body); break;
                    case QConjugate c: Scan(c.Within); Scan(c.Apply); break;
                }
        }
        Scan(op.Body);
        return map;
    }

    /// <summary>
    /// Bit comparisons emit against BOOL literals: `r == 1` → `r == true`, `r != 0` → `r != false`
    /// (either operand order) whenever the name is a known bit. Both spellings are valid OpenQASM 3,
    /// but the dominant consumer (Qiskit's qasm3 importer) accepts only `bit == const bool` — so emit
    /// the one that actually loads. Ints and unknown names are left untouched.
    /// </summary>
    private static string RewriteBitCond(string text, Dictionary<string, string> varTypes)
    {
        var toks = text.Split(' ');

        // OpenQASM has no logical `!` on a classical scalar (it reads a bit/int/float as a numeric
        // literal, not a bool): rewrite a negated classical value `! ( x )` to `x == 0` (a bit then
        // becomes `x == false` via the loop below). Qora source keeps `!x`; only the emitted QASM changes
        // — the same emit-time adjustment as `s == 1` -> `s == true`.
        var neg = new List<string>(toks.Length);
        for (var i = 0; i < toks.Length; i++)
            if (toks[i] == "!" && i + 3 < toks.Length && toks[i + 1] == "(" && varTypes.ContainsKey(toks[i + 2]) && toks[i + 3] == ")")
            {
                neg.Add(toks[i + 2]); neg.Add("=="); neg.Add("0");
                i += 3;
            }
            else neg.Add(toks[i]);
        toks = neg.ToArray();

        for (var i = 0; i + 2 < toks.Length; i++)
        {
            if (toks[i + 1] is not ("==" or "!=")) continue;
            if (IsBit(toks[i]) && toks[i + 2] is "0" or "1") toks[i + 2] = toks[i + 2] == "1" ? "true" : "false";
            else if (IsBit(toks[i + 2]) && toks[i] is "0" or "1") toks[i] = toks[i] == "1" ? "true" : "false";
        }
        return string.Join(" ", toks);

        bool IsBit(string tok) => varTypes.TryGetValue(tok, out var t) && t == "bit";
    }

    private static string EmitParam(QParam p) => p.Type switch
    {
        QType.Int => $"int {p.Name}",
        QType.Bit => $"bit {p.Name}",
        QType.Float => $"float {p.Name}",
        QType.Angle => $"angle {p.Name}",
        _ => p.RegisterSize is int n ? $"qubit[{n}] {p.Name}" : $"qubit {p.Name}",
    };

    private static string RenderArg(QArg arg) => arg switch
    {
        QQubitArg q => $"{q.Reg}[{q.Index}]",
        QTextArg t => t.Text,
        _ => string.Empty,
    };

    private static string RenderExpr(QExpr expr) => expr switch
    {
        QMeasure m => m.Target is null ? "measure" : $"measure {m.Target.Reg}[{m.Target.Index}]",
        QText t => t.Text,
        _ => string.Empty,
    };

    private static string MapGate(string name) =>
        QoraGates.Names.TryGetValue(name, out var qasm) ? qasm : name.ToLowerInvariant();

    private static string? TypeName(QType? t) => t switch { QType.Int => "int", QType.Bit => "bit", QType.Float => "float", QType.Angle => "angle", _ => null };
}
