using System.Text;

namespace Qora.Ir;

/// <summary>
/// Pure OpenQASM 3 printer for <see cref="MirOpenQasmTargetProgram"/>. Every name, type, call edge,
/// modifier, and structured-control decision is already frozen in the target AST; this class reads no
/// HIR, MIR, semantic model, source map, or compiler-global naming state.
/// </summary>
public static class MirQasmEmitter
{
    public static string Emit(MirOpenQasmTargetProgram program)
    {
        ArgumentNullException.ThrowIfNull(program);

        var callableNames = program.Definitions.ToDictionary(
            definition => definition.Id,
            definition => definition.EmittedName);
        var writer = new Writer(callableNames);
        var text = new StringBuilder();
        text.AppendLine($"// generated by Qora v{QoraVersion.Value}");
        text.AppendLine("OPENQASM 3;");
        text.AppendLine("include \"stdgates.inc\";");
        foreach (var note in program.Notes)
            text.AppendLine($"// Qora: {note}");

        foreach (var definition in OrderDefinitions(program.Definitions))
        {
            text.AppendLine();
            writer.EmitDefinition(definition, text);
        }

        if (program.EntryBody.Length > 0)
            text.AppendLine();
        writer.EmitEntry(program.EntryBody, text);
        return text.ToString().TrimEnd();
    }

    /// <summary>
    /// OpenQASM requires a definition before every use. Dependencies are discovered exclusively through
    /// typed target callable IDs, never by comparing final spellings.
    /// </summary>
    internal static IReadOnlyList<MirQasmCallableDefinition> OrderDefinitions(
        IReadOnlyList<MirQasmCallableDefinition> definitions)
    {
        var byId = definitions.ToDictionary(definition => definition.Id);
        var stableIndex = definitions
            .Select((definition, index) => (definition.Id, index))
            .ToDictionary(item => item.Id, item => item.index);
        var dependencies = definitions.ToDictionary(
            definition => definition.Id,
            definition => CollectDependencies(definition.Body));
        var indegree = definitions.ToDictionary(
            definition => definition.Id,
            definition => dependencies[definition.Id].Count);
        var dependents = definitions.ToDictionary(
            definition => definition.Id,
            _ => new List<MirQasmCallableId>());

        foreach (var (caller, callees) in dependencies)
        {
            foreach (var callee in callees)
            {
                if (!byId.ContainsKey(callee))
                    throw new InvalidOperationException(
                        $"QINTERNAL: target callable {caller} depends on missing callable {callee}");
                dependents[callee].Add(caller);
            }
        }

        var ready = new SortedSet<(int Index, int Id)>();
        foreach (var definition in definitions)
            if (indegree[definition.Id] == 0)
                ready.Add((stableIndex[definition.Id], definition.Id.Value));

        var ordered = new List<MirQasmCallableDefinition>(definitions.Count);
        while (ready.Count > 0)
        {
            var next = ready.Min;
            ready.Remove(next);
            var id = new MirQasmCallableId(next.Id);
            ordered.Add(byId[id]);
            foreach (var caller in dependents[id])
            {
                indegree[caller]--;
                if (indegree[caller] == 0)
                    ready.Add((stableIndex[caller], caller.Value));
            }
        }

        if (ordered.Count != definitions.Count)
        {
            var cyclic = definitions
                .Where(definition => indegree[definition.Id] > 0)
                .Select(definition => $"{definition.EmittedName} ({definition.Id})");
            throw new InvalidOperationException(
                "QINTERNAL: OpenQASM target definitions contain a call cycle: " +
                string.Join(", ", cyclic));
        }

        return ordered;
    }

    private static HashSet<MirQasmCallableId> CollectDependencies(
        IReadOnlyList<MirQasmStatement> statements)
    {
        var dependencies = new HashSet<MirQasmCallableId>();
        foreach (var statement in statements)
        {
            switch (statement)
            {
                case MirQasmValueDeclarationStatement { Initializer: { } initializer }:
                    VisitExpression(initializer);
                    break;
                case MirQasmArrayDeclarationStatement declaration:
                    foreach (var element in declaration.Elements)
                        VisitExpression(element);
                    break;
                case MirQasmAssignmentStatement assignment:
                    VisitExpression(assignment.Target);
                    VisitExpression(assignment.Value);
                    break;
                case MirQasmMeasurementAssignmentStatement measurement:
                    VisitExpression(measurement.Target);
                    VisitExpression(measurement.Qubit);
                    break;
                case MirQasmQuantumApplyStatement apply:
                    if (apply.Target is MirQasmUserQuantumTarget user)
                        dependencies.Add(user.Callable);
                    foreach (var parameter in apply.GateParameters)
                        VisitExpression(parameter);
                    foreach (var operand in apply.Operands)
                        VisitExpression(operand);
                    break;
                case MirQasmIfStatement branch:
                    VisitExpression(branch.Condition);
                    dependencies.UnionWith(CollectDependencies(branch.Then));
                    dependencies.UnionWith(CollectDependencies(branch.Else));
                    break;
                case MirQasmWhileStatement loop:
                    VisitExpression(loop.Condition);
                    dependencies.UnionWith(CollectDependencies(loop.Body));
                    break;
                case MirQasmReturnStatement { Value: { } value }:
                    VisitExpression(value);
                    break;
            }
        }
        return dependencies;

        void VisitExpression(MirQasmExpression expression)
        {
            switch (expression)
            {
                case MirQasmUnaryExpression unary:
                    VisitExpression(unary.Operand);
                    break;
                case MirQasmBinaryExpression binary:
                    VisitExpression(binary.Left);
                    VisitExpression(binary.Right);
                    break;
                case MirQasmIndexExpression index:
                    VisitExpression(index.Base);
                    VisitExpression(index.Index);
                    break;
                case MirQasmSizeOfExpression size:
                    VisitExpression(size.Operand);
                    break;
                case MirQasmUnsignedCastExpression cast:
                    VisitExpression(cast.Operand);
                    break;
                case MirQasmFunctionCallExpression call:
                    if (call.Target is MirQasmUserFunctionTarget user)
                        dependencies.Add(user.Callable);
                    foreach (var argument in call.Arguments)
                        VisitExpression(argument);
                    break;
            }
        }
    }

    private sealed class Writer
    {
        private readonly IReadOnlyDictionary<MirQasmCallableId, string> _callableNames;

        public Writer(IReadOnlyDictionary<MirQasmCallableId, string> callableNames) =>
            _callableNames = callableNames;

        public void EmitDefinition(
            MirQasmCallableDefinition definition,
            StringBuilder text)
        {
            var bindings = BindingNames.For(definition.Parameters, definition.Body);
            var parameters = string.Join(
                ", ",
                definition.Parameters.Select(RenderParameter));
            var returns = definition.ReturnType is { } returnType
                ? $" -> {RenderReturnType(returnType)}"
                : string.Empty;
            text.AppendLine($"def {definition.EmittedName}({parameters}){returns} {{");
            EmitStatements(definition.Body, text, indent: 1, bindings);
            text.AppendLine("}");
        }

        public void EmitEntry(
            IReadOnlyList<MirQasmStatement> body,
            StringBuilder text)
        {
            var bindings = BindingNames.For(
                Array.Empty<MirQasmParameter>(),
                body);
            EmitStatements(body, text, indent: 0, bindings);
        }

        private void EmitStatements(
            IReadOnlyList<MirQasmStatement> statements,
            StringBuilder text,
            int indent,
            BindingNames bindings)
        {
            var pad = new string(' ', indent * 2);
            foreach (var statement in statements)
            {
                switch (statement)
                {
                    case MirQasmValueDeclarationStatement declaration:
                    {
                        var prefix = declaration.IsConst ? "const " : string.Empty;
                        var initializer = declaration.Initializer is { } initializerValue
                            ? $" = {Render(initializerValue, bindings)}"
                            : string.Empty;
                        text.AppendLine(
                            $"{pad}{prefix}{RenderValueType(declaration.Type)} " +
                            $"{declaration.EmittedName}{initializer};");
                        break;
                    }

                    case MirQasmArrayDeclarationStatement declaration:
                        text.AppendLine(
                            $"{pad}{RenderDeclarationType(declaration.Type)} " +
                            $"{declaration.EmittedName} = " +
                            $"{{{string.Join(", ", declaration.Elements.Select(element => Render(element, bindings)))}}};");
                        break;

                    case MirQasmQubitDeclarationStatement declaration:
                        text.AppendLine(
                            $"{pad}{RenderDeclarationType(declaration.Type)} {declaration.EmittedName};");
                        break;

                    case MirQasmAssignmentStatement assignment:
                        text.AppendLine(
                            $"{pad}{Render(assignment.Target, bindings)} = " +
                            $"{Render(assignment.Value, bindings)};");
                        break;

                    case MirQasmMeasurementAssignmentStatement measurement:
                        text.AppendLine(
                            $"{pad}{Render(measurement.Target, bindings)} = measure " +
                            $"{Render(measurement.Qubit, bindings)};");
                        break;

                    case MirQasmQuantumApplyStatement apply:
                        text.AppendLine($"{pad}{RenderQuantumApply(apply, bindings)}");
                        break;

                    case MirQasmIfStatement branch:
                        text.AppendLine($"{pad}if ({Render(branch.Condition, bindings)}) {{");
                        EmitStatements(branch.Then, text, indent + 1, bindings);
                        text.AppendLine($"{pad}}}");
                        if (branch.Else.Length > 0)
                        {
                            text.AppendLine($"{pad}else {{");
                            EmitStatements(branch.Else, text, indent + 1, bindings);
                            text.AppendLine($"{pad}}}");
                        }
                        break;

                    case MirQasmWhileStatement loop:
                        text.AppendLine($"{pad}while ({Render(loop.Condition, bindings)}) {{");
                        EmitStatements(loop.Body, text, indent + 1, bindings);
                        text.AppendLine($"{pad}}}");
                        break;

                    case MirQasmReturnStatement returned:
                        text.AppendLine(
                            returned.Value is { } value
                                ? $"{pad}return {Render(value, bindings)};"
                                : $"{pad}return;");
                        break;

                    case MirQasmBreakStatement:
                        text.AppendLine($"{pad}break;");
                        break;

                    default:
                        throw new InvalidOperationException(
                            $"QINTERNAL: unhandled target statement {statement.GetType().Name}");
                }
            }
        }

        private string RenderQuantumApply(
            MirQasmQuantumApplyStatement apply,
            BindingNames bindings)
        {
            var modifier = string.Concat(apply.Modifiers.Select(RenderModifier));
            if (apply.Target is MirQasmUserQuantumTarget user)
            {
                var name = RequireCallable(user.Callable);
                return
                    $"{name}({string.Join(", ", apply.Operands.Select(operand => Render(operand, bindings)))});";
            }

            var builtin = (MirQasmBuiltinGateTarget)apply.Target;
            var parameters = apply.GateParameters.Length == 0
                ? string.Empty
                : $"({string.Join(", ", apply.GateParameters.Select(parameter => Render(parameter, bindings)))})";
            var operands = string.Join(
                ", ",
                apply.Operands.Select(operand => Render(operand, bindings)));
            return operands.Length == 0
                ? $"{modifier}{builtin.EmittedName}{parameters};"
                : $"{modifier}{builtin.EmittedName}{parameters} {operands};";
        }

        private string Render(
            MirQasmExpression expression,
            BindingNames bindings,
            int parentPrecedence = 0,
            bool rightOperand = false)
        {
            var precedence = Precedence(expression);
            var rendered = expression switch
            {
                MirQasmLiteralExpression literal =>
                    literal.Text,
                MirQasmParameterReferenceExpression parameter =>
                    bindings.Parameter(parameter.Parameter),
                MirQasmDeclarationReferenceExpression declaration =>
                    bindings.Declaration(declaration.Declaration),
                MirQasmUnaryExpression unary =>
                    $"{RenderUnary(unary.Operator)}" +
                    $"{Render(unary.Operand, bindings, precedence)}",
                MirQasmBinaryExpression binary =>
                    $"{Render(binary.Left, bindings, precedence)} " +
                    $"{RenderBinary(binary.Operator)} " +
                    $"{Render(binary.Right, bindings, precedence, rightOperand: true)}",
                MirQasmIndexExpression index =>
                    $"{Render(index.Base, bindings, precedence)}" +
                    $"[{Render(index.Index, bindings)}]",
                MirQasmSizeOfExpression size =>
                    $"sizeof({Render(size.Operand, bindings)})",
                MirQasmUnsignedCastExpression cast =>
                    $"uint[{cast.Width}]({Render(cast.Operand, bindings)})",
                MirQasmFunctionCallExpression call =>
                    $"{RenderFunctionTarget(call.Target)}" +
                    $"({string.Join(", ", call.Arguments.Select(argument => Render(argument, bindings)))})",
                _ => throw new InvalidOperationException(
                    $"QINTERNAL: unhandled target expression {expression.GetType().Name}"),
            };

            return precedence < parentPrecedence
                   || rightOperand
                   && expression is MirQasmBinaryExpression
                   && precedence == parentPrecedence
                ? $"({rendered})"
                : rendered;
        }

        private string RenderFunctionTarget(MirQasmFunctionTarget target) =>
            target switch
            {
                MirQasmBuiltinFunctionTarget builtin => builtin.EmittedName,
                MirQasmUserFunctionTarget user => RequireCallable(user.Callable),
                _ => throw new InvalidOperationException(
                    $"QINTERNAL: unhandled function target {target.GetType().Name}"),
            };

        private string RequireCallable(MirQasmCallableId callable) =>
            _callableNames.TryGetValue(callable, out var name)
                ? name
                : throw new InvalidOperationException(
                    $"QINTERNAL: missing emitted name for target callable {callable}");

        private static string RenderParameter(MirQasmParameter parameter)
        {
            if (parameter.Type is MirQasmArrayType array)
            {
                var access = parameter.Access switch
                {
                    MirQasmParameterAccess.ReadOnly => "readonly",
                    MirQasmParameterAccess.Mutable => "mutable",
                    _ => throw new InvalidOperationException(
                        "QINTERNAL: a target array parameter has no access mode"),
                };
                return
                    $"{access} array[{RenderScalarType(array.ElementType)}, #dim = 1] " +
                    $"{parameter.EmittedName}";
            }

            return $"{RenderDeclarationType(parameter.Type)} {parameter.EmittedName}";
        }

        private static string RenderReturnType(MirQasmType type) =>
            type switch
            {
                MirQasmScalarType scalar => RenderScalarType(scalar),
                MirQasmBitType { IsRegister: false } => "bit",
                _ => throw new InvalidOperationException(
                    $"QINTERNAL: unsupported OpenQASM return type {type}"),
            };

        private static string RenderValueType(MirQasmType type) =>
            type switch
            {
                MirQasmScalarType scalar => RenderScalarType(scalar),
                MirQasmBitType bit =>
                    bit.IsRegister ? $"bit[{bit.Width}]" : "bit",
                _ => throw new InvalidOperationException(
                    $"QINTERNAL: unsupported OpenQASM value type {type}"),
            };

        private static string RenderDeclarationType(MirQasmType type) =>
            type switch
            {
                MirQasmScalarType scalar => RenderScalarType(scalar),
                MirQasmBitType bit =>
                    bit.IsRegister ? $"bit[{bit.Width}]" : "bit",
                MirQasmQubitType qubit =>
                    qubit.IsRegister ? $"qubit[{qubit.Count}]" : "qubit",
                MirQasmArrayType { Length: int length } array =>
                    $"array[{RenderScalarType(array.ElementType)}, {length}]",
                MirQasmArrayType =>
                    throw new InvalidOperationException(
                        "QINTERNAL: a target array declaration has no concrete length"),
                _ => throw new InvalidOperationException(
                    $"QINTERNAL: unsupported OpenQASM declaration type {type}"),
            };

        private static string RenderScalarType(MirQasmScalarType type) =>
            type.Kind switch
            {
                MirQasmScalarKind.Int => "int",
                MirQasmScalarKind.UInt => "uint",
                MirQasmScalarKind.Float => "float",
                MirQasmScalarKind.Angle => "angle",
                MirQasmScalarKind.Bool => "bool",
                _ => throw new InvalidOperationException(
                    $"QINTERNAL: unknown OpenQASM scalar kind {type.Kind}"),
            };

        private static string RenderModifier(MirQasmQuantumModifier modifier) =>
            modifier switch
            {
                MirQasmQuantumModifier.Inverse => "inv @ ",
                MirQasmQuantumModifier.Controlled => "ctrl @ ",
                _ => throw new InvalidOperationException(
                    $"QINTERNAL: unknown quantum modifier {modifier}"),
            };

        private static string RenderUnary(MirQasmUnaryOperator @operator) =>
            @operator switch
            {
                MirQasmUnaryOperator.Negate => "-",
                MirQasmUnaryOperator.LogicalNot => "!",
                _ => throw new InvalidOperationException(
                    $"QINTERNAL: unknown unary operator {@operator}"),
            };

        private static string RenderBinary(MirQasmBinaryOperator @operator) =>
            @operator switch
            {
                MirQasmBinaryOperator.LogicalOr => "||",
                MirQasmBinaryOperator.LogicalAnd => "&&",
                MirQasmBinaryOperator.Equal => "==",
                MirQasmBinaryOperator.NotEqual => "!=",
                MirQasmBinaryOperator.Less => "<",
                MirQasmBinaryOperator.LessOrEqual => "<=",
                MirQasmBinaryOperator.Greater => ">",
                MirQasmBinaryOperator.GreaterOrEqual => ">=",
                MirQasmBinaryOperator.Add => "+",
                MirQasmBinaryOperator.Subtract => "-",
                MirQasmBinaryOperator.Multiply => "*",
                MirQasmBinaryOperator.Divide => "/",
                MirQasmBinaryOperator.Modulo => "%",
                _ => throw new InvalidOperationException(
                    $"QINTERNAL: unknown binary operator {@operator}"),
            };

        private static int Precedence(MirQasmExpression expression) =>
            expression switch
            {
                MirQasmBinaryExpression binary => binary.Operator switch
                {
                    MirQasmBinaryOperator.LogicalOr => 10,
                    MirQasmBinaryOperator.LogicalAnd => 20,
                    MirQasmBinaryOperator.Equal or MirQasmBinaryOperator.NotEqual => 30,
                    MirQasmBinaryOperator.Less or MirQasmBinaryOperator.LessOrEqual
                        or MirQasmBinaryOperator.Greater or MirQasmBinaryOperator.GreaterOrEqual => 40,
                    MirQasmBinaryOperator.Add or MirQasmBinaryOperator.Subtract => 50,
                    MirQasmBinaryOperator.Multiply or MirQasmBinaryOperator.Divide
                        or MirQasmBinaryOperator.Modulo => 60,
                    _ => throw new InvalidOperationException(
                        $"QINTERNAL: unknown binary operator {binary.Operator}"),
                },
                MirQasmUnaryExpression => 70,
                MirQasmIndexExpression or MirQasmFunctionCallExpression
                    or MirQasmSizeOfExpression or MirQasmUnsignedCastExpression => 80,
                _ => 90,
            };
    }

    private sealed class BindingNames
    {
        private readonly IReadOnlyDictionary<MirQasmParameterId, string> _parameters;
        private readonly IReadOnlyDictionary<MirQasmDeclarationId, string> _declarations;

        private BindingNames(
            IReadOnlyDictionary<MirQasmParameterId, string> parameters,
            IReadOnlyDictionary<MirQasmDeclarationId, string> declarations)
        {
            _parameters = parameters;
            _declarations = declarations;
        }

        public static BindingNames For(
            IReadOnlyList<MirQasmParameter> parameters,
            IReadOnlyList<MirQasmStatement> statements)
        {
            var parameterNames = parameters.ToDictionary(
                parameter => parameter.Id,
                parameter => parameter.EmittedName);
            var declarationNames = new Dictionary<MirQasmDeclarationId, string>();
            Collect(statements);
            return new BindingNames(parameterNames, declarationNames);

            void Collect(IReadOnlyList<MirQasmStatement> body)
            {
                foreach (var statement in body)
                {
                    switch (statement)
                    {
                        case MirQasmValueDeclarationStatement declaration:
                            declarationNames.Add(declaration.Declaration, declaration.EmittedName);
                            break;
                        case MirQasmArrayDeclarationStatement declaration:
                            declarationNames.Add(declaration.Declaration, declaration.EmittedName);
                            break;
                        case MirQasmQubitDeclarationStatement declaration:
                            declarationNames.Add(declaration.Declaration, declaration.EmittedName);
                            break;
                        case MirQasmIfStatement branch:
                            Collect(branch.Then);
                            Collect(branch.Else);
                            break;
                        case MirQasmWhileStatement loop:
                            Collect(loop.Body);
                            break;
                    }
                }
            }
        }

        public string Parameter(MirQasmParameterId id) =>
            _parameters.TryGetValue(id, out var name)
                ? name
                : throw new InvalidOperationException(
                    $"QINTERNAL: missing emitted name for target parameter {id}");

        public string Declaration(MirQasmDeclarationId id) =>
            _declarations.TryGetValue(id, out var name)
                ? name
                : throw new InvalidOperationException(
                    $"QINTERNAL: missing emitted name for target declaration {id}");
    }
}
