using System.Text;

namespace Qora.Ir;

/// <summary>
/// Prints a fully legalized <see cref="OpenQasmTargetProgram"/> as OpenQASM 3.0 text. This final pass
/// invents no names, infers no types, rebuilds no HIR scopes, and inverts no bodies. Whole-operation
/// <c>Adjoint</c> on a user op is already gone by now — <see cref="AdjointMaterializer"/> turned each into
/// an ordinary call to a synthesized inverse def (a real op), so this emitter sees only plain defs and
/// plain calls.
///
/// OpenQASM requires declare-before-use for defs and has no forward declarations, so all defs are emitted
/// in dependency (topological) order; on a call cycle — only reachable through forward recursion, which
/// validation (QSEM011) already rejects — it falls back to the stable order.
///
/// The functors that DO reach here are on BUILT-IN gates: <c>Adjoint H</c> → <c>inv @ h</c>,
/// <c>Controlled X</c> → <c>ctrl @ x</c>. A functor left on a user op (which validation forbids — QSEM002
/// for Controlled, and Adjoint is materialized away) is emitted as a visible <c>// Qora:</c> note rather
/// than invalid text, as is a modifier on <c>reset</c> (a statement, not a gate).
/// </summary>
public static class QasmEmitter
{
    private static readonly Dictionary<string, string> FunctorMods = new()
    {
        ["Adjoint"] = "inv @ ",
        ["Controlled"] = "ctrl @ ",
    };

    /// <summary>
    /// Everything statement emission needs to classify a call site. User callability is determined by
    /// Resolver's declaration ID; final names are used only as serialization text.
    /// </summary>
    private sealed record Ctx(
        IReadOnlyDictionary<int, QOperation> Operations);

    public static string Emit(OpenQasmTargetProgram target)
    {
        ArgumentNullException.ThrowIfNull(target);

        var program = target.Program;
        if (program.Operations.Count == 0) return string.Empty;
        var operations = program.Operations;
        var entry = operations.FirstOrDefault(o => o.Name == "Main") ?? operations[0];
        var subroutines = operations.Where(o => o != entry).ToList();

        var opById = operations.ToDictionary(operation => operation.Id);
        var ctx = new Ctx(opById);

        var sb = new StringBuilder();
        // provenance: emitted QASM files travel alone (papers, repos) — record which compiler made them.
        sb.AppendLine($"// generated by Qora v{QoraVersion.Value}");
        // name collisions were auto-resolved by NameMangler; surface each rename here so a reader who sees
        // an adjusted def name knows why (only present when a collision actually occurred).
        foreach (var note in target.Notes)
            sb.AppendLine($"// Qora: {note}");
        sb.AppendLine("OPENQASM 3;");
        sb.AppendLine("include \"stdgates.inc\";");

        // Synthesized inverse defs are ordinary ops by this point (AdjointMaterializer), so every def is
        // emitted the same way, in dependency order.
        foreach (var operationId in OrderDefs(subroutines, entry.Id, opById, ctx))
        {
            sb.AppendLine();
            EmitDef(opById[operationId], ctx, sb, target.Types);
        }

        sb.AppendLine();
        var decls = new StringBuilder();
        HoistDecls(entry.Body, decls, target.Types);
        var body = new StringBuilder();
        EmitStatements(
            entry.Body,
            body,
            0,
            ctx,
            SeedVarTypes(entry, target.Types),
            target.Types);
        sb.Append(decls);
        sb.Append(body);

        return sb.ToString().TrimEnd();
    }

    /// <summary>
    /// Focused emitter seam for tests that hand-build an already-legal target tree. Every classical
    /// declaration must have an explicit type; production compilation must enter through
    /// <see cref="QasmBackend"/> and <see cref="Emit(OpenQasmTargetProgram)"/>.
    /// </summary>
    internal static string EmitExplicitForTesting(
        QProgram program,
        IReadOnlyList<string>? notes = null) =>
        Emit(OpenQasmTargetProgram.CreateExplicitForTesting(program, notes));

    // --- def ordering (declare-before-use) ---

    /// <summary>
    /// Order all defs so every def appears before its callers: Kahn's algorithm over the call graph,
    /// tie-broken by the stable order (subroutines in source order, then synthesized inverse defs in
    /// discovery order — the order <see cref="AdjointMaterializer"/> appended them). A cycle — possible
    /// only via forward recursion, which OpenQASM cannot express anyway — falls back to appending stably.
    /// </summary>
    private static List<int> OrderDefs(
        List<QOperation> subroutines,
        int entryOperationId,
        IReadOnlyDictionary<int, QOperation> operationsById,
        Ctx ctx)
    {
        var nodes = subroutines.Select(operation => operation.Id).ToList();
        var index = new Dictionary<int, int>();
        for (int i = 0; i < nodes.Count; i++) index[nodes[i]] = i;

        // edges: callee -> callers (a def depends on the defs it calls)
        var dependents = new Dictionary<int, List<int>>();
        var indegree = new int[nodes.Count];
        for (int i = 0; i < nodes.Count; i++)
        {
            var deps = new HashSet<int>();
            CollectCallDeps(
                operationsById[nodes[i]].Body,
                entryOperationId,
                ctx,
                deps);
            foreach (var dep in deps)
            {
                if (!index.TryGetValue(dep, out var j) || j == i) continue;
                if (!dependents.TryGetValue(j, out var list)) dependents[j] = list = new List<int>();
                list.Add(i);
                indegree[i]++;
            }
        }

        var result = new List<int>();
        var emitted = new bool[nodes.Count];
        while (result.Count < nodes.Count)
        {
            var next = -1;
            for (int i = 0; i < nodes.Count; i++)
                if (!emitted[i] && indegree[i] == 0) { next = i; break; }
            if (next < 0) // cycle: emit the stably-first remaining node anyway
                for (int i = 0; i < nodes.Count; i++)
                    if (!emitted[i]) { next = i; break; }

            emitted[next] = true;
            result.Add(nodes[next]);
            if (dependents.TryGetValue(next, out var users))
                foreach (var u in users) indegree[u]--;
        }
        return result;
    }

    /// <summary>
    /// Collect which defs a body's call sites reference. Statement calls live on <see cref="QGate"/>;
    /// function calls live inside any expression-bearing statement as <see cref="QCallNode"/>. Both edges
    /// participate in definition ordering, so a caller is never emitted before a function it invokes.
    /// Functors on user operations never reach here: Adjoint is materialized and Controlled is invalid.
    /// </summary>
    private static void CollectCallDeps(
        IReadOnlyList<QStmt> stmts,
        int entryOperationId,
        Ctx ctx,
        HashSet<int> into)
    {
        foreach (var stmt in stmts)
        {
            foreach (var tree in QNodes.ExpressionSites(stmt))
                foreach (var call in QNodes.CallsIn(tree))
                    if (call.CalleeOpId is int expressionCalleeId)
                    {
                        RequireKnownOperation(
                            expressionCalleeId,
                            call.Name,
                            ctx);
                        if (expressionCalleeId != entryOperationId)
                            into.Add(expressionCalleeId);
                    }

            switch (stmt)
            {
                case QGate { CalleeOpId: int gateCalleeId } gate:
                    RequireKnownOperation(
                        gateCalleeId,
                        gate.Name,
                        ctx);
                    if (gateCalleeId != entryOperationId)
                        into.Add(gateCalleeId);
                    break;
                case QIf i:
                    CollectCallDeps(i.Then, entryOperationId, ctx, into);
                    CollectCallDeps(i.Else, entryOperationId, ctx, into);
                    break;
                case QFor f:
                    CollectCallDeps(f.Body, entryOperationId, ctx, into);
                    break;
                case QWhile w:
                    CollectCallDeps(w.Body, entryOperationId, ctx, into);
                    break;
                case QRepeat r:
                    CollectCallDeps(r.Body, entryOperationId, ctx, into);
                    break;
                case QConjugate c:
                    CollectCallDeps(c.Within, entryOperationId, ctx, into);
                    CollectCallDeps(c.Apply, entryOperationId, ctx, into);
                    break;
            }
        }
    }

    // --- def emission ---

    private static void EmitDef(
        QOperation op,
        Ctx ctx,
        StringBuilder sb,
        OpenQasmTypeEnvironment types)
    {
        var ps = string.Join(
            ", ",
            op.Params.Select(parameter => EmitParam(parameter, types)));
        var decls = new StringBuilder();
        HoistDecls(op.Body, decls, types);
        var body = new StringBuilder();
        EmitStatements(
            op.Body,
            body,
            1,
            ctx,
            SeedVarTypes(op, types),
            types);

        // A function emits its trailing return type (`def two() -> int { … }`); an operation is void. The
        // emitter is a PURE PRINTER: it renders the IR as-is. A `return` that OpenQASM/Braket cannot lower
        // from inside a nested block is restructured by a dedicated QASM pass BEFORE emission, never here.
        var ret = op.IsFunction && op.ReturnType is { } rt ? $" -> {TypeName(rt)}" : string.Empty;
        sb.AppendLine($"def {op.Name}({ps}){ret} {{");
        foreach (var line in decls.ToString().Split('\n'))
            if (line.Trim().Length > 0) sb.AppendLine($"  {line.TrimEnd()}");
        sb.Append(body);
        sb.AppendLine("}");
    }

    private static void HoistDecls(
        IReadOnlyList<QStmt> stmts,
        StringBuilder decls,
        OpenQasmTypeEnvironment types) =>
        HoistDecls(stmts, decls, new HashSet<string>(), types);

    // Qubit registers AND measure bits are hoisted to the top of the def body. Registers because `use` is
    // entry-top-level only (QSEM012); measure bits because OpenQASM importers (e.g. Qiskit) accept only
    // GLOBAL classical declarations, not local ones inside a control-flow block — so a measure written deep
    // in an `if`/`for`/`repeat` emits its `bit r;` here at the top and just an `r = measure …;` assignment
    // in place (see EmitDecl). This is purely an EMISSION shape: the source language keeps measure bits
    // block-scoped (a use outside the declaring block is QSEM025). Hoisted names are deduplicated by name —
    // the same measure bit declared in both branches of an if/else must become ONE top-level `bit r;`
    // (QASM's top scope is flat). The symbol table guarantees no two hoisted names (register/param/measure
    // bit) collide across enclosing scopes, so the flattening here is always sound.
    private static void HoistDecls(
        IReadOnlyList<QStmt> stmts,
        StringBuilder decls,
        HashSet<string> seen,
        OpenQasmTypeEnvironment types)
    {
        foreach (var stmt in stmts)
        {
            switch (stmt)
            {
                case QUse u:
                    if (seen.Add(u.Name)) decls.AppendLine($"qubit[{u.Size}] {u.Name};");
                    break;
                case QDecl d when d.Value is QMeasure:
                    if (seen.Add(d.Name))
                    {
                        var targetType = types.GetType(d.Id);
                        if (targetType.IsArray)
                            throw new InvalidOperationException(
                                $"QINTERNAL: measurement declaration `{d.Name}` has an array target type");
                        var typeName = TypeName(targetType.ElementType)
                            ?? throw new InvalidOperationException(
                                $"QINTERNAL: measurement declaration `{d.Name}` has no printable target type");
                        decls.AppendLine($"{typeName} {d.Name};");
                    }
                    break;
                case QIf i:
                    HoistDecls(i.Then, decls, seen, types);
                    HoistDecls(i.Else, decls, seen, types);
                    break;
                case QFor f:
                    HoistDecls(f.Body, decls, seen, types);
                    break;
                case QWhile w:
                    HoistDecls(w.Body, decls, seen, types);
                    break;
                case QRepeat r:
                    HoistDecls(r.Body, decls, seen, types);
                    break;
                case QConjugate c:
                    // Defensive only — ConjugationLowering removes every QConjugate before emission. If one
                    // somehow survived, still hoist any declarations nested inside it rather than losing them
                    // (ReferentialCheck raises the QINTERNAL that actually blocks this output). NOT a blanket
                    // `default:` — this switch deliberately lets gates/assigns/classical decls fall through.
                    HoistDecls(c.Within, decls, seen, types);
                    HoistDecls(c.Apply, decls, seen, types);
                    break;
            }
        }
    }

    private static void EmitStatements(
        IReadOnlyList<QStmt> stmts,
        StringBuilder body,
        int indent,
        Ctx ctx,
        Dictionary<string, string> varTypes,
        OpenQasmTypeEnvironment types)
    {
        var pad = new string(' ', indent * 2);

        foreach (var stmt in stmts)
        {
            switch (stmt)
            {
                case QUse:
                    break; // hoisted

                case QGate g:
                    body.AppendLine(pad + EmitStmtInline(g, ctx));
                    break;

                case QDecl d:
                    EmitDecl(d, body, pad, varTypes, types);
                    break;

                case QAssign a:
                    var target = a.Index is null ? a.Name : $"{a.Name}[{RenderNode(a.Index)}]";
                    body.AppendLine($"{pad}{target} = {RenderExpr(a.Value)};");
                    break;

                case QIf i:
                    EmitIf(i, body, indent, ctx, varTypes, types);
                    break;

                case QFor f:
                    var range = f.Step is null
                        ? $"[{RenderNode(f.From)}:{RenderNode(f.To)}]"
                        : $"[{RenderNode(f.From)}:{RenderNode(f.Step)}:{RenderNode(f.To)}]";
                    body.AppendLine($"{pad}for int {f.Var} in {range} {{");
                    EmitStatements(f.Body, body, indent + 1, ctx, varTypes, types);
                    body.AppendLine($"{pad}}}");
                    break;

                case QWhile w:
                    body.AppendLine($"{pad}while ({RenderCond(w.Cond, varTypes)}) {{");
                    EmitStatements(w.Body, body, indent + 1, ctx, varTypes, types);
                    body.AppendLine($"{pad}}}");
                    break;

                case QRepeat r:
                    body.AppendLine($"{pad}while (true) {{");
                    EmitStatements(r.Body, body, indent + 1, ctx, varTypes, types);
                    body.AppendLine($"{pad}  if ({RenderCond(r.Until, varTypes)}) {{ break; }}");
                    body.AppendLine($"{pad}}}");
                    break;

                case QReturn ret:
                    body.AppendLine($"{pad}return {RenderExpr(ret.Value)};");
                    break;

                case QBreak:
                    body.AppendLine($"{pad}break;");
                    break;

                default:
                    // Defense in depth: every real QStmt has a case above, and an un-flattened QConjugate is
                    // already turned into a QINTERNAL error by ReferentialCheck (which gates this emission),
                    // so this is unreachable in a successful compile. Still, emit a VISIBLE marker rather than
                    // silently dropping a statement — a silent drop was the original latent bug.
                    body.AppendLine($"{pad}// Qora: internal error — unhandled {stmt.GetType().Name} reached the emitter");
                    break;
            }
        }
    }

    private static void EmitIf(
        QIf node,
        StringBuilder body,
        int indent,
        Ctx ctx,
        Dictionary<string, string> varTypes,
        OpenQasmTypeEnvironment types)
    {
        var pad = new string(' ', indent * 2);

        body.AppendLine($"{pad}if ({RenderCond(node.Cond, varTypes)}) {{");
        EmitStatements(node.Then, body, indent + 1, ctx, varTypes, types);
        body.AppendLine($"{pad}}}");

        if (node.Else.Count > 0)
        {
            body.AppendLine($"{pad}else {{");
            EmitStatements(node.Else, body, indent + 1, ctx, varTypes, types);
            body.AppendLine($"{pad}}}");
        }
    }

    /// <summary>Render one gate/call/functor invocation as a single line (used inline and inside adj defs).</summary>
    private static string EmitStmtInline(QStmt stmt, Ctx ctx)
    {
        if (stmt is not QGate gate) return string.Empty;

        var name = gate.Name;
        var isUserOp = false;
        if (gate.CalleeOpId is int operationId)
        {
            RequireKnownOperation(operationId, name, ctx);
            isUserOp = true;
        }
        var args = gate.Args.Select(RenderArg).ToList();
        var modifier = string.Concat(gate.Functors.Select(f => FunctorMods.TryGetValue(f, out var m) ? m : string.Empty));

        // A functor on a user op has no lowering (OpenQASM modifiers apply to gates, not defs) and does
        // not occur in validated, materialized IR — whole-op Adjoint became a plain inverse-def call and
        // Controlled on a user op is QSEM002. Kept as a visible note in case an unvalidated path reaches here.
        if (isUserOp && gate.Functors.Count > 0)
            return $"// Qora: {gate.Functors[0]} of `{name}` has no OpenQASM lowering (a modifier cannot apply to a def)";

        // reset is a statement, not a gate — it takes no modifiers.
        if (gate.Functors.Count > 0 && MapGate(name) == "reset")
            return $"// Qora: {string.Join(" ", gate.Functors)} {name} is not supported (reset is not a gate and takes no modifiers)";

        if (QoraGates.Rotations.Contains(name) && args.Count >= 2)
            return $"{modifier}{MapGate(name)}({args[0]}) {string.Join(", ", args.Skip(1))};";

        return isUserOp
            ? $"{modifier}{name}({string.Join(", ", args)});"
            : $"{modifier}{MapGate(name)} {string.Join(", ", args)};";
    }

    private static void RequireKnownOperation(
        int operationId,
        string callName,
        Ctx ctx)
    {
        if (!ctx.Operations.ContainsKey(operationId))
            throw new InvalidOperationException(
                $"QINTERNAL: target call `{callName}` carries dangling CalleeOpId {operationId}");
    }

    private static void EmitDecl(
        QDecl d,
        StringBuilder body,
        string pad,
        Dictionary<string, string> varTypes,
        OpenQasmTypeEnvironment types)
    {
        var targetType = types.GetType(d.Id);
        if (d.IsArray != targetType.IsArray)
            throw new InvalidOperationException(
                $"QINTERNAL: declaration `{d.Name}` disagrees with its OpenQASM target array shape");

        if (targetType.IsArray)
        {
            var elementType = TypeName(targetType.ElementType) ?? throw new InvalidOperationException(
                $"QINTERNAL: array `{d.Name}` reached emission without an element type");
            var length = d.Value switch
            {
                QArrayLiteral literal => literal.Elements.Count,
                QArrayNew allocation => allocation.Length,
                _ => throw new InvalidOperationException(
                    $"QINTERNAL: array `{d.Name}` reached emission without an array initializer"),
            };
            // varTypes drives the bit-condition rewrite (`if (f[1] == true)`). The ARRAY marker matters:
            // an ELEMENT of a bit array is a scalar bit (rewritten), but the WHOLE register compared to an
            // int (`f == 1`) is a numeric register comparison — valid QASM that must NOT be rewritten to
            // a bool. Recording the bare element type under the array's name once conflated the two.
            varTypes.TryAdd(d.Name, elementType + "[]");

            // `bit` is the one element type that cannot take the general form: "bit, bit[n] and stretch are
            // not valid array base types" (OpenQASM 3, types.rst). Bits get the dedicated register type.
            if (targetType.ElementType == QType.Bit)
            {
                EmitBitRegisterDecl(d, length, body, pad);
                return;
            }

            var initializer = d.Value switch
            {
                QArrayLiteral literal => string.Join(", ", literal.Elements.Select(RenderExpr)),
                QArrayNew allocation => string.Join(", ", Enumerable.Repeat(DefaultValue(allocation.ElementType), allocation.Length)),
                _ => string.Empty,
            };
            body.AppendLine($"{pad}array[{elementType}, {length}] {d.Name} = {{{initializer}}};");
            return;
        }

        if (d.Value is QMeasure)
        {
            // The `bit r;` declaration is hoisted to the top of the def body (HoistDecls) for OpenQASM
            // importer compatibility; here we emit only the assignment, in place. Source-level block scoping
            // is enforced separately by the symbol table (out-of-block use = QSEM025).
            body.AppendLine($"{pad}{d.Name} = {RenderExpr(d.Value)};");
            return;
        }

        // A validated untyped declaration already has one inferred type in the target type environment.
        // Emission is deliberately incapable of guessing it again from the initializer.
        var type = TypeName(targetType.ElementType)
            ?? throw new InvalidOperationException(
                $"QINTERNAL: declaration `{d.Name}` reached OpenQASM emission without a target type");
        varTypes.TryAdd(d.Name, type);
        var prefix = d.IsConst ? "const " : string.Empty;
        body.AppendLine($"{pad}{prefix}{type} {d.Name} = {RenderExpr(d.Value)};");
    }

    /// <summary>
    /// A <c>bit[]</c> declaration, as OpenQASM's dedicated <c>bit[N]</c> register.
    /// <para><c>new bit[N]</c> emits the all-zeros bitstring rather than a bare <c>bit[N] f;</c>, because a
    /// bare register is UNDEFINED, not zeroed, and Qora's <c>new T[N]</c> promises zero-initialization for
    /// every other element type. An all-zeros string is the same read either way, so the ordering caveat
    /// below cannot bite it.</para>
    /// <para>An array LITERAL is written element by element and never as a bitstring: the spec's prose puts
    /// element 0 at the RIGHT (least-significant) end while Braket reads it at the LEFT, so any non-uniform
    /// bitstring would silently reverse the array. Indexed writes mean the same thing on both.</para>
    /// </summary>
    private static void EmitBitRegisterDecl(QDecl d, int length, StringBuilder body, string pad)
    {
        if (d.Value is QArrayNew)
        {
            body.AppendLine($"{pad}bit[{length}] {d.Name} = \"{new string('0', length)}\";");
            return;
        }

        var literal = (QArrayLiteral)d.Value!;
        body.AppendLine($"{pad}bit[{length}] {d.Name};");
        for (var i = 0; i < literal.Elements.Count; i++)
            body.AppendLine($"{pad}{d.Name}[{i}] = {RenderExpr(literal.Elements[i])};");
    }

    private static string DefaultValue(QType type) => type switch
    {
        QType.Float or QType.Angle => "0.0",
        _ => "0",
    };

    /// <summary>
    /// Build the flat per-operation emitted-name → type view used by condition rendering. The authoritative
    /// facts already live in <paramref name="types"/> keyed by declaration Id; this walk only joins those
    /// facts to the final names in the target tree. No semantic lookup or inference happens here.
    /// </summary>
    private static Dictionary<string, string> SeedVarTypes(
        QOperation op,
        OpenQasmTypeEnvironment types)
    {
        var map = new Dictionary<string, string>();

        void AddNamed(string currentName, int nodeId)
        {
            var targetType = types.GetType(nodeId);
            var name = TypeName(targetType.ElementType)
                ?? throw new InvalidOperationException(
                    $"QINTERNAL: declaration `{currentName}` has no printable OpenQASM type");
            map[currentName] = targetType.IsArray ? name + "[]" : name;
        }

        void Level(IReadOnlyList<QStmt> stmts)
        {
            foreach (var s in stmts)
                if (s is QDecl d)
                    AddNamed(d.Name, d.Id);
            foreach (var s in stmts)
            {
                switch (s)
                {
                    case QFor f:
                        AddNamed(f.Var, f.Id);
                        Level(f.Body);
                        break;
                    case QIf i:
                        Level(i.Then);
                        Level(i.Else);
                        break;
                    case QWhile w:
                        Level(w.Body);
                        break;
                    case QRepeat r:
                        Level(r.Body);
                        break;
                    case QConjugate c:
                        Level(c.Within);
                        Level(c.Apply);
                        break;
                }
            }
        }

        foreach (var parameter in op.Params)
            if (parameter.Type != QType.Qubit)
                AddNamed(parameter.Name, parameter.Id);
        Level(op.Body);
        return map;
    }

    /// <summary>Render a condition for emission: the tree is bit-rewritten (<see cref="RewriteBits"/>)
    /// then printed.</summary>
    private static string RenderCond(QCond cond, Dictionary<string, string> varTypes) =>
        cond.Tree is null ? string.Empty : RenderNode(RewriteBits(cond.Tree, varTypes));

    /// <summary>
    /// The bit-condition adjustments, on the tree. WHY: OpenQASM has no logical <c>!</c> on a classical
    /// scalar, so a negated known-classical value <c>!x</c> becomes <c>x == 0</c>; and bit comparisons
    /// emit against BOOL literals — <c>r == 1</c> → <c>r == true</c>, <c>r != 0</c> → <c>r != false</c>
    /// (either operand order) — because the dominant consumer (Qiskit's qasm3 importer) accepts only
    /// <c>bit == const bool</c>. Applied bottom-up so every comparison under <c>&amp;&amp;</c>/<c>||</c>
    /// is rewritten, and the negation's <c>== 0</c> result immediately becomes <c>== false</c> for a bit.
    /// Ints and unknown names are left untouched.
    /// </summary>
    private static QNode RewriteBits(QNode node, Dictionary<string, string> varTypes)
    {
        node = node switch
        {
            QUnary u => u with { Operand = RewriteBits(u.Operand, varTypes) },
            QBinOp b => b with { Left = RewriteBits(b.Left, varTypes), Right = RewriteBits(b.Right, varTypes) },
            OpenQasmUnsignedCastNode cast => cast with
            {
                Operand = RewriteBits(cast.Operand, varTypes),
            },
            _ => node,
        };
        // `!x` is Qora's "x is zero/false" and OpenQASM has no logical NOT on a numeric value, so it is
        // ALWAYS rewritten to the comparison `x == 0` — a BLANKET rule, never conditional on being able to
        // type the operand. Gating it on a known type silently emitted `! ( sizeof(a) )` for a compound
        // operand (a `.Count`, a function call, arithmetic), which the target rejects
        // ("Invalid operator ! for IntegerLiteral"). A `bit` operand is then further rewritten to
        // `x == false` by the comparison handling below, exactly as before.
        if (node is QUnary { Op: "!", Operand: { } inner })
            node = new QBinOp("==", inner, new QNumLit(0));
        if (node is QBinOp { Op: "==" or "!=" } cmp)
        {
            if (TypeOfNode(cmp.Left, varTypes) == "bit" && cmp.Right is QNumLit { Value: 0 or 1 } rn)
                return cmp with { Right = new QLit(rn.Value == 1 ? "true" : "false") };
            if (TypeOfNode(cmp.Right, varTypes) == "bit" && cmp.Left is QNumLit { Value: 0 or 1 } ln)
                return cmp with { Left = new QLit(ln.Value == 1 ? "true" : "false") };
        }
        // NOTE: a WHOLE bit register needs NO adjustment here, and deliberately gets none. It can only have
        // reached an expression at all as `f == g` against another register of the same width (QSEM036), which
        // OpenQASM compares as bit patterns — exactly Qora's meaning — so it prints as written. Every reading
        // of a register AS A NUMBER is spelled `AsInt(f)` in the source and became a width-qualified
        // `uint[N](f)` in OpenQasmLowering, before this printer ever saw it.
        return node;
    }

    /// <summary>The emitted SCALAR type of a directly-referenced value — a bare scalar name, or one array
    /// element (whose type is the array's element type, stored as <c>"T[]"</c> under the array's name).
    /// A bare ARRAY name has no scalar type (a whole-register comparison is numeric, never bit-rewritten);
    /// compound expressions have no single lookup type.</summary>
    private static string? TypeOfNode(QNode node, Dictionary<string, string> varTypes) => node switch
    {
        QNameRef r => varTypes.TryGetValue(r.Name, out var t) && !t.EndsWith("[]") ? t : null,
        QIndexNode { Base: QNameRef b } => varTypes.TryGetValue(b.Name, out var t) && t.EndsWith("[]") ? t[..^2] : null,
        _ => null,
    };

    private static string EmitParam(
        QParam p,
        OpenQasmTypeEnvironment types)
    {
        if (p.Type == QType.Qubit)
        {
            return p switch
            {
                { RegisterSize: int n } => $"qubit[{n}] {p.Name}",
                { IsQubitArray: true } => throw new InvalidOperationException(
                    $"QINTERNAL: unspecialized Qubit[] parameter `{p.Name}` reached OpenQASM emission"),
                _ => $"qubit {p.Name}",
            };
        }

        var targetType = types.GetType(p.Id);
        if (targetType.IsArray)
        {
            // bit is not a valid array base type (types.rst) — a bit[] parameter's only legal form is
            // the sized register, so monomorphization must stamp its width before target emission.
            if (targetType.ElementType == QType.Bit)
            {
                return p.RegisterSize is int bits
                    ? $"bit[{bits}] {p.Name}"
                    : throw new InvalidOperationException(
                        $"QINTERNAL: unspecialized bit[] parameter `{p.Name}` reached OpenQASM emission");
            }

            var elementType = TypeName(targetType.ElementType)
                ?? throw new InvalidOperationException(
                    $"QINTERNAL: array parameter `{p.Name}` has no printable OpenQASM element type");
            return
                $"{(p.Access == QAccessMode.Mutable ? "mutable" : "readonly")} " +
                $"array[{elementType}, #dim = 1] {p.Name}";
        }

        return TypeName(targetType.ElementType) is { } scalarType
            ? $"{scalarType} {p.Name}"
            : throw new InvalidOperationException(
                $"QINTERNAL: parameter `{p.Name}` has no printable OpenQASM target type");
    }

    private static string RenderArg(QArg arg) => arg switch
    {
        QQubitArg q => $"{q.Reg}[{RenderNode(q.Index)}]",
        QTextArg t => RenderNode(t.Tree),
        _ => string.Empty,
    };

    private static string RenderExpr(QExpr expr) => expr switch
    {
        QMeasure m => $"measure {RenderNode(m.Target)}",
        QText t => RenderNode(t.Tree),
        QArrayLiteral literal => $"{{{string.Join(", ", literal.Elements.Select(RenderExpr))}}}",
        QArrayNew allocation => $"{{{string.Join(", ", Enumerable.Repeat(DefaultValue(allocation.ElementType), allocation.Length))}}}",
        _ => string.Empty,
    };

    /// <summary>
    /// Render an expression TREE as OpenQASM text — the emitter's own spelling, distinct from the
    /// canonical IR spelling (<see cref="QNodes.Render"/>): <c>.Count</c> becomes <c>sizeof(base)</c> and
    /// an indexed access glues (<c>q[i]</c>) — exactly the two rewrites the historical text path applied
    /// by regex over the stored text. Operators keep their single-space joins; no precedence parens are
    /// inserted (trees come from a paren-free grammar and rewrites substitute leaves only, so the in-order
    /// token run re-parses to the same structure).
    /// </summary>
    private static string RenderNode(QNode? node) => node switch
    {
        null => string.Empty,
        QNumLit n => n.Value.ToString(System.Globalization.CultureInfo.InvariantCulture),
        QLit l => l.Text,
        QNameRef r => r.Name,
        QMember { Member: "Count" } m => $"sizeof({RenderNode(m.Base)})",
        QMember m => $"{RenderNode(m.Base)} . {m.Member}",   // non-Count members never survive validation
        QUnary { Op: "!" } u => $"! ( {RenderNode(u.Operand)} )",
        QUnary u => $"{u.Op} {RenderOperand(u.Operand, parent: 5, isRight: true)}",
        QBinOp b => $"{RenderOperand(b.Left, Prec(b.Op))} {b.Op} {RenderOperand(b.Right, Prec(b.Op), isRight: true)}",
        QIndexNode i => $"{RenderNode(i.Base)}[{RenderNode(i.Index)}]",
        OpenQasmUnsignedCastNode cast => $"uint[{cast.Width}]({RenderNode(cast.Operand)})",
        QCallNode c => $"{c.Name}({string.Join(", ", c.Args.Select(RenderNode))})",
        _ => string.Empty,
    };

    /// <summary>Render a binary/unary operand, parenthesizing ONLY when the emitted token run would
    /// re-parse to a different grouping than the tree: a child that binds strictly LOOSER than its parent
    /// (any side), or a SAME-precedence child on the RIGHT (the operators are left-associative, so
    /// <c>n == m == 0</c> re-parses as <c>(n == m) == 0</c> — the opposite of a tree holding
    /// <c>n == (m == 0)</c>). No PARSED tree holds either shape (the precedence parse builds left-leaning
    /// trees whose right children always bind strictly tighter), but a REWRITE can synthesize both —
    /// <see cref="RewriteBits"/> substitutes <c>m == 0</c> for <c>!m</c> wherever the negation sat.
    /// Natural trees never trigger this, so their emitted bytes are unchanged.</summary>
    private static string RenderOperand(QNode child, int parent, bool isRight = false) =>
        child is QBinOp cb && (Prec(cb.Op) < parent || (isRight && Prec(cb.Op) == parent))
            ? $"( {RenderNode(child)} )"
            : RenderNode(child);

    /// <summary>OpenQASM 3's (C-style) binding strength: <c>||</c> &lt; <c>&amp;&amp;</c> &lt; equality
    /// &lt; relational &lt; additive &lt; multiplicative — the ladder the emitted text re-parses under.</summary>
    private static int Prec(string op) => op switch
    {
        "||" => 1,
        "&&" => 2,
        "==" or "!=" => 3,
        "<" or "<=" or ">" or ">=" => 4,
        "+" or "-" => 5,
        "*" or "/" => 6,
        _ => 7,
    };

    private static string MapGate(string name) =>
        QoraGates.Names.TryGetValue(name, out var qasm) ? qasm : name.ToLowerInvariant();

    private static string? TypeName(QType? t) => t switch { QType.Int => "int", QType.Bit => "bit", QType.Float => "float", QType.Angle => "angle", _ => null };
}
