using System.Text;

namespace Qora.Ir;

/// <summary>
/// Lowers Qora IR (<see cref="QProgram"/>) to OpenQASM 3.0 — the final, text-producing pass, and a pure
/// printer: it invents no names and inverts no bodies. Whole-operation <c>Adjoint</c> on a user op is
/// already gone by now — <see cref="AdjointMaterializer"/> turned each into an ordinary call to a
/// synthesized inverse def (a real op), so this emitter sees only plain defs and plain calls.
///
/// OpenQASM requires declare-before-use for defs and has no forward declarations, so all defs are emitted
/// in dependency (topological) order; on a call cycle — only reachable through forward recursion, which
/// validation (QSEM011) already rejects — it falls back to the stable order.
///
/// The functors that DO reach here are on BUILT-IN gates: <c>Adjoint H</c> → <c>inv @ h</c>,
/// <c>Controlled X</c> → <c>ctrl @ x</c>. A functor left on a user op (which validation forbids — QSEM002
/// for Controlled, and Adjoint is materialized away) is emitted as a visible <c>// Qora:</c> note rather
/// than invalid text, as is a modifier on <c>reset</c> (a statement, not a gate).
/// </summary>
public static class QasmEmitter
{
    private static readonly Dictionary<string, string> FunctorMods = new()
    {
        ["Adjoint"] = "inv @ ",
        ["Controlled"] = "ctrl @ ",
    };

    /// <summary>Everything statement emission needs to resolve a call site: the set of user-op names
    /// (so a call to one prints as a def call, not a stdgate). Inversion left no state to carry.</summary>
    private sealed record Ctx(HashSet<string> Ops);

    public static string Emit(QProgram? program, IReadOnlyList<string>? notes = null, Passes.SemanticModel? model = null)
    {
        if (program is null || program.Operations.Count == 0) return string.Empty;

        var operations = program.Operations;
        var entry = operations.FirstOrDefault(o => o.Name == "Main") ?? operations[0];
        var subroutines = operations.Where(o => o != entry).ToList();
        var ops = operations.Select(o => o.Name).ToHashSet();

        var opByName = new Dictionary<string, QOperation>();
        foreach (var o in operations) opByName[o.Name] = o;
        var ctx = new Ctx(ops);

        var sb = new StringBuilder();
        // provenance: emitted QASM files travel alone (papers, repos) — record which compiler made them.
        sb.AppendLine($"// generated by Qora v{QoraVersion.Value}");
        // name collisions were auto-resolved by NameMangler; surface each rename here so a reader who sees
        // an adjusted def name knows why (only present when a collision actually occurred).
        if (notes is not null)
            foreach (var note in notes) sb.AppendLine($"// Qora: {note}");
        sb.AppendLine("OPENQASM 3;");
        sb.AppendLine("include \"stdgates.inc\";");

        // Synthesized inverse defs are ordinary ops by this point (AdjointMaterializer), so every def is
        // emitted the same way, in dependency order.
        foreach (var name in OrderDefs(subroutines, entry.Name, opByName, ctx))
        {
            sb.AppendLine();
            EmitDef(opByName[name], ctx, sb, model);
        }

        sb.AppendLine();
        var decls = new StringBuilder();
        HoistDecls(entry.Body, decls);
        var body = new StringBuilder();
        EmitStatements(entry.Body, body, 0, ctx, SeedVarTypes(entry, model));
        sb.Append(decls);
        sb.Append(body);

        return sb.ToString().TrimEnd();
    }

    // --- def ordering (declare-before-use) ---

    /// <summary>
    /// Order all defs so every def appears before its callers: Kahn's algorithm over the call graph,
    /// tie-broken by the stable order (subroutines in source order, then synthesized inverse defs in
    /// discovery order — the order <see cref="AdjointMaterializer"/> appended them). A cycle — possible
    /// only via forward recursion, which OpenQASM cannot express anyway — falls back to appending stably.
    /// </summary>
    private static List<string> OrderDefs(
        List<QOperation> subroutines, string entryName, Dictionary<string, QOperation> opByName, Ctx ctx)
    {
        var nodes = subroutines.Select(s => s.Name).ToList();
        var index = new Dictionary<string, int>();
        for (int i = 0; i < nodes.Count; i++) index[nodes[i]] = i;

        // edges: callee -> callers (a def depends on the defs it calls)
        var dependents = new Dictionary<int, List<int>>();
        var indegree = new int[nodes.Count];
        for (int i = 0; i < nodes.Count; i++)
        {
            var deps = new HashSet<string>();
            CollectCallDeps(opByName[nodes[i]].Body, entryName, ctx, deps);
            foreach (var dep in deps)
            {
                if (!index.TryGetValue(dep, out var j) || j == i) continue;
                if (!dependents.TryGetValue(j, out var list)) dependents[j] = list = new List<int>();
                list.Add(i);
                indegree[i]++;
            }
        }

        var result = new List<string>();
        var emitted = new bool[nodes.Count];
        while (result.Count < nodes.Count)
        {
            var next = -1;
            for (int i = 0; i < nodes.Count; i++)
                if (!emitted[i] && indegree[i] == 0) { next = i; break; }
            if (next < 0) // cycle: emit the stably-first remaining node anyway
                for (int i = 0; i < nodes.Count; i++)
                    if (!emitted[i]) { next = i; break; }

            emitted[next] = true;
            result.Add(nodes[next]);
            if (dependents.TryGetValue(next, out var users))
                foreach (var u in users) indegree[u]--;
        }
        return result;
    }

    /// <summary>Collect which defs a body's call sites reference: every plain call to a user op (functors
    /// on a user op never reach here — Adjoint is materialized away, Controlled is a validation error).</summary>
    private static void CollectCallDeps(IReadOnlyList<QStmt> stmts, string entryName, Ctx ctx, HashSet<string> into)
    {
        foreach (var stmt in stmts)
        {
            switch (stmt)
            {
                case QGate g when ctx.Ops.Contains(g.Name) && g.Name != entryName && g.Functors.Count == 0:
                    into.Add(g.Name);
                    break;
                case QIf i:
                    CollectCallDeps(i.Then, entryName, ctx, into);
                    CollectCallDeps(i.Else, entryName, ctx, into);
                    break;
                case QFor f:
                    CollectCallDeps(f.Body, entryName, ctx, into);
                    break;
                case QWhile w:
                    CollectCallDeps(w.Body, entryName, ctx, into);
                    break;
                case QRepeat r:
                    CollectCallDeps(r.Body, entryName, ctx, into);
                    break;
                case QConjugate c:
                    CollectCallDeps(c.Within, entryName, ctx, into);
                    CollectCallDeps(c.Apply, entryName, ctx, into);
                    break;
            }
        }
    }

    // --- def emission ---

    private static void EmitDef(QOperation op, Ctx ctx, StringBuilder sb, Passes.SemanticModel? model)
    {
        var ps = string.Join(", ", op.Params.Select(EmitParam));
        var decls = new StringBuilder();
        HoistDecls(op.Body, decls);
        var body = new StringBuilder();
        EmitStatements(op.Body, body, 1, ctx, SeedVarTypes(op, model));

        // A function emits its trailing return type (`def two() -> int { … }`); an operation is void. The
        // emitter is a PURE PRINTER: it renders the IR as-is. A `return` that OpenQASM/Braket cannot lower
        // from inside a nested block is restructured by a dedicated QASM pass BEFORE emission, never here.
        var ret = op.IsFunction && op.ReturnType is { } rt ? $" -> {TypeName(rt)}" : string.Empty;
        sb.AppendLine($"def {op.Name}({ps}){ret} {{");
        foreach (var line in decls.ToString().Split('\n'))
            if (line.Trim().Length > 0) sb.AppendLine($"  {line.TrimEnd()}");
        sb.Append(body);
        sb.AppendLine("}");
    }

    private static void HoistDecls(IReadOnlyList<QStmt> stmts, StringBuilder decls) =>
        HoistDecls(stmts, decls, new HashSet<string>());

    // Qubit registers AND measure bits are hoisted to the top of the def body. Registers because `use` is
    // entry-top-level only (QSEM012); measure bits because OpenQASM importers (e.g. Qiskit) accept only
    // GLOBAL classical declarations, not local ones inside a control-flow block — so a measure written deep
    // in an `if`/`for`/`repeat` emits its `bit r;` here at the top and just an `r = measure …;` assignment
    // in place (see EmitDecl). This is purely an EMISSION shape: the source language keeps measure bits
    // block-scoped (a use outside the declaring block is QSEM025). Hoisted names are deduplicated by name —
    // the same measure bit declared in both branches of an if/else must become ONE top-level `bit r;`
    // (QASM's top scope is flat). The symbol table guarantees no two hoisted names (register/param/measure
    // bit) collide across enclosing scopes, so the flattening here is always sound.
    private static void HoistDecls(IReadOnlyList<QStmt> stmts, StringBuilder decls, HashSet<string> seen)
    {
        foreach (var stmt in stmts)
        {
            switch (stmt)
            {
                case QUse u:
                    if (seen.Add(u.Name)) decls.AppendLine($"qubit[{u.Size}] {u.Name};");
                    break;
                case QDecl d when d.Value is QMeasure:
                    if (seen.Add(d.Name)) decls.AppendLine($"{TypeName(d.Type) ?? "bit"} {d.Name};");
                    break;
                case QIf i:
                    HoistDecls(i.Then, decls, seen);
                    HoistDecls(i.Else, decls, seen);
                    break;
                case QFor f:
                    HoistDecls(f.Body, decls, seen);
                    break;
                case QWhile w:
                    HoistDecls(w.Body, decls, seen);
                    break;
                case QRepeat r:
                    HoistDecls(r.Body, decls, seen);
                    break;
                case QConjugate c:
                    // Defensive only — ConjugationLowering removes every QConjugate before emission. If one
                    // somehow survived, still hoist any declarations nested inside it rather than losing them
                    // (ReferentialCheck raises the QINTERNAL that actually blocks this output). NOT a blanket
                    // `default:` — this switch deliberately lets gates/assigns/classical decls fall through.
                    HoistDecls(c.Within, decls, seen);
                    HoistDecls(c.Apply, decls, seen);
                    break;
            }
        }
    }

    private static void EmitStatements(IReadOnlyList<QStmt> stmts, StringBuilder body, int indent, Ctx ctx, Dictionary<string, string> varTypes)
    {
        var pad = new string(' ', indent * 2);

        foreach (var stmt in stmts)
        {
            switch (stmt)
            {
                case QUse:
                    break; // hoisted

                case QGate g:
                    body.AppendLine(pad + EmitStmtInline(g, ctx));
                    break;

                case QDecl d:
                    EmitDecl(d, body, pad, varTypes);
                    break;

                case QAssign a:
                    var target = a.Index is null ? a.Name : $"{a.Name}[{RenderNode(a.Index)}]";
                    body.AppendLine($"{pad}{target} = {RenderExpr(a.Value)};");
                    break;

                case QIf i:
                    EmitIf(i, body, indent, ctx, varTypes);
                    break;

                case QFor f:
                    var range = f.Step is null
                        ? $"[{RenderNode(f.From)}:{RenderNode(f.To)}]"
                        : $"[{RenderNode(f.From)}:{RenderNode(f.Step)}:{RenderNode(f.To)}]";
                    body.AppendLine($"{pad}for int {f.Var} in {range} {{");
                    EmitStatements(f.Body, body, indent + 1, ctx, varTypes);
                    body.AppendLine($"{pad}}}");
                    break;

                case QWhile w:
                    body.AppendLine($"{pad}while ({RenderCond(w.Cond, varTypes)}) {{");
                    EmitStatements(w.Body, body, indent + 1, ctx, varTypes);
                    body.AppendLine($"{pad}}}");
                    break;

                case QRepeat r:
                    body.AppendLine($"{pad}while (true) {{");
                    EmitStatements(r.Body, body, indent + 1, ctx, varTypes);
                    body.AppendLine($"{pad}  if ({RenderCond(r.Until, varTypes)}) {{ break; }}");
                    body.AppendLine($"{pad}}}");
                    break;

                case QReturn ret:
                    body.AppendLine($"{pad}return {RenderExpr(ret.Value)};");
                    break;

                case QBreak:
                    body.AppendLine($"{pad}break;");
                    break;

                default:
                    // Defense in depth: every real QStmt has a case above, and an un-flattened QConjugate is
                    // already turned into a QINTERNAL error by ReferentialCheck (which gates this emission),
                    // so this is unreachable in a successful compile. Still, emit a VISIBLE marker rather than
                    // silently dropping a statement — a silent drop was the original latent bug.
                    body.AppendLine($"{pad}// Qora: internal error — unhandled {stmt.GetType().Name} reached the emitter");
                    break;
            }
        }
    }

    private static void EmitIf(QIf node, StringBuilder body, int indent, Ctx ctx, Dictionary<string, string> varTypes)
    {
        var pad = new string(' ', indent * 2);

        body.AppendLine($"{pad}if ({RenderCond(node.Cond, varTypes)}) {{");
        EmitStatements(node.Then, body, indent + 1, ctx, varTypes);
        body.AppendLine($"{pad}}}");

        if (node.Else.Count > 0)
        {
            body.AppendLine($"{pad}else {{");
            EmitStatements(node.Else, body, indent + 1, ctx, varTypes);
            body.AppendLine($"{pad}}}");
        }
    }

    /// <summary>Render one gate/call/functor invocation as a single line (used inline and inside adj defs).</summary>
    private static string EmitStmtInline(QStmt stmt, Ctx ctx)
    {
        if (stmt is not QGate gate) return string.Empty;

        var name = gate.Name;
        var isUserOp = ctx.Ops.Contains(name);
        var args = gate.Args.Select(RenderArg).ToList();
        var modifier = string.Concat(gate.Functors.Select(f => FunctorMods.TryGetValue(f, out var m) ? m : string.Empty));

        // A functor on a user op has no lowering (OpenQASM modifiers apply to gates, not defs) and does
        // not occur in validated, materialized IR — whole-op Adjoint became a plain inverse-def call and
        // Controlled on a user op is QSEM002. Kept as a visible note in case an unvalidated path reaches here.
        if (isUserOp && gate.Functors.Count > 0)
            return $"// Qora: {gate.Functors[0]} of `{name}` has no OpenQASM lowering (a modifier cannot apply to a def)";

        // reset is a statement, not a gate — it takes no modifiers.
        if (gate.Functors.Count > 0 && MapGate(name) == "reset")
            return $"// Qora: {string.Join(" ", gate.Functors)} {name} is not supported (reset is not a gate and takes no modifiers)";

        if (QoraGates.Rotations.Contains(name) && args.Count >= 2)
            return $"{modifier}{MapGate(name)}({args[0]}) {string.Join(", ", args.Skip(1))};";

        return isUserOp
            ? $"{modifier}{name}({string.Join(", ", args)});"
            : $"{modifier}{MapGate(name)} {string.Join(", ", args)};";
    }

    private static void EmitDecl(QDecl d, StringBuilder body, string pad, Dictionary<string, string> varTypes)
    {
        if (d.IsArray)
        {
            var elementType = TypeName(d.Type) ?? throw new InvalidOperationException(
                $"QINTERNAL: array `{d.Name}` reached emission without an element type");
            var length = d.Value switch
            {
                QArrayLiteral literal => literal.Elements.Count,
                QArrayNew allocation => allocation.Length,
                _ => throw new InvalidOperationException(
                    $"QINTERNAL: array `{d.Name}` reached emission without an array initializer"),
            };
            // varTypes drives the bit-condition rewrite (`if (f[1] == true)`). The ARRAY marker matters:
            // an ELEMENT of a bit array is a scalar bit (rewritten), but the WHOLE register compared to an
            // int (`f == 1`) is a numeric register comparison — valid QASM that must NOT be rewritten to
            // a bool. Recording the bare element type under the array's name once conflated the two.
            varTypes.TryAdd(d.Name, elementType + "[]");

            // `bit` is the one element type that cannot take the general form: "bit, bit[n] and stretch are
            // not valid array base types" (OpenQASM 3, types.rst). Bits get the dedicated register type.
            if (d.Type == QType.Bit)
            {
                EmitBitRegisterDecl(d, length, body, pad);
                return;
            }

            var initializer = d.Value switch
            {
                QArrayLiteral literal => string.Join(", ", literal.Elements.Select(RenderExpr)),
                QArrayNew allocation => string.Join(", ", Enumerable.Repeat(DefaultValue(allocation.ElementType), allocation.Length)),
                _ => string.Empty,
            };
            body.AppendLine($"{pad}array[{elementType}, {length}] {d.Name} = {{{initializer}}};");
            return;
        }

        if (d.Value is QMeasure)
        {
            // The `bit r;` declaration is hoisted to the top of the def body (HoistDecls) for OpenQASM
            // importer compatibility; here we emit only the assignment, in place. Source-level block scoping
            // is enforced separately by the symbol table (out-of-block use = QSEM025).
            body.AppendLine($"{pad}{d.Name} = {RenderExpr(d.Value)};");
            return;
        }

        var type = TypeName(d.Type) ?? InferDefaultType(d.Value, varTypes);
        varTypes.TryAdd(d.Name, type);
        var prefix = d.IsConst ? "const " : string.Empty;
        body.AppendLine($"{pad}{prefix}{type} {d.Name} = {RenderExpr(d.Value)};");
    }

    /// <summary>
    /// A <c>bit[]</c> declaration, as OpenQASM's dedicated <c>bit[N]</c> register.
    /// <para><c>new bit[N]</c> emits the all-zeros bitstring rather than a bare <c>bit[N] f;</c>, because a
    /// bare register is UNDEFINED, not zeroed, and Qora's <c>new T[N]</c> promises zero-initialization for
    /// every other element type. An all-zeros string is the same read either way, so the ordering caveat
    /// below cannot bite it.</para>
    /// <para>An array LITERAL is written element by element and never as a bitstring: the spec's prose puts
    /// element 0 at the RIGHT (least-significant) end while Braket reads it at the LEFT, so any non-uniform
    /// bitstring would silently reverse the array. Indexed writes mean the same thing on both.</para>
    /// </summary>
    private static void EmitBitRegisterDecl(QDecl d, int length, StringBuilder body, string pad)
    {
        if (d.Value is QArrayNew)
        {
            body.AppendLine($"{pad}bit[{length}] {d.Name} = \"{new string('0', length)}\";");
            return;
        }

        var literal = (QArrayLiteral)d.Value!;
        body.AppendLine($"{pad}bit[{length}] {d.Name};");
        for (var i = 0; i < literal.Elements.Count; i++)
            body.AppendLine($"{pad}{d.Name}[{i}] = {RenderExpr(literal.Elements[i])};");
    }

    private static string DefaultValue(QType type) => type switch
    {
        QType.Float or QType.Angle => "0.0",
        _ => "0",
    };

    /// <summary>
    /// The emitted type of an untyped `var`/`const`, inferred from its initializer using the type map (which
    /// the symbol table seeds, so a referenced name's type — including a bit — is known):
    /// <list type="bullet">
    ///   <item><b>float</b> — a real-valued initializer: a float literal, a built-in constant, or a name
    ///         already known float/angle (so floatness propagates: `var a = pi; var b = a / 2;`). `int t = pi
    ///         / 4;` would be an invalid narrowing.</item>
    ///   <item><b>bit</b> — a lone bit reference (`var x = r;` where `r` is a bit); emitting `int x = r;`
    ///         would be a wrong-typed (bit→int) declaration.</item>
    ///   <item><b>int</b> — everything else (the default).</item>
    /// </list>
    /// </summary>
    private static string InferDefaultType(QExpr value, Dictionary<string, string> varTypes)
    {
        if (value is not QText t) return "int";

        // Structurally: a float literal, a built-in constant, a float/angle name, or a float-array element
        // anywhere makes the whole initializer float. A member (.Count) is an integer length — the token
        // scan misread its DOT as a float marker; the structure cannot.
        bool IsFloaty(QNode? n) => n switch
        {
            QLit l => l.Text.Contains('.'),
            QNameRef r => r.Name is "pi" or "tau" or "euler"
                || (varTypes.TryGetValue(r.Name, out var vt) && vt is "float" or "angle" or "float[]" or "angle[]"),
            QUnary u => IsFloaty(u.Operand),
            QBinOp b => IsFloaty(b.Left) || IsFloaty(b.Right),
            QIndexNode i => IsFloaty(i.Base),   // a float-array ELEMENT is a float
            _ => false,   // QNumLit, QMember (.Count is an int), QCallNode
        };
        if (IsFloaty(t.Tree)) return "float";
        if (t.Tree is QNameRef single && varTypes.TryGetValue(single.Name, out var st) && st == "bit")
            return "bit";
        return "int";
    }

    /// <summary>
    /// The per-op map of every classical name to its emitted type. It is derived from the ONE source of
    /// name→type — the symbol table — rather than re-scanned by hand, so NO declaration kind can be missed:
    /// parameters, <c>use</c> registers, vars, consts, measure bits AND loop variables all carry their type
    /// there (a hand-rolled scan previously forgot loop variables, so `!i` emitted an invalid `! ( i )`).
    /// Qubits and untyped <c>var</c>s are absent — a qubit is never a classical value, and an untyped var's
    /// type is inferred at its declaration by <see cref="InferDefaultType"/> and added then. It is a flat
    /// whole-op superset, so bit-typed rendering (`r == 1` → `r == true`) and the classical `!x` → `x == 0`
    /// rewrite are consistent wherever the name resolves; block scoping guarantees no use before declaration.
    ///
    /// With a <see cref="Passes.SemanticModel"/> the map is READ, not rebuilt: each declaring node's CURRENT
    /// (post-mangling) name is paired with its validation-time type through the node's stable Id — the exact
    /// current-name ↔ proven-type join a rebuild cannot express (a rebuild sees mangled names only). The
    /// walk mirrors the scope tree's <see cref="Passes.Scope.AllSymbols"/> order (this level's declarations,
    /// then nested blocks in program order) so shadowed names resolve to the same final entry either way.
    /// Without a model (standalone <see cref="Emit"/> call), the old full rebuild remains as the fallback.
    /// </summary>
    private static Dictionary<string, string> SeedVarTypes(QOperation op, Passes.SemanticModel? model)
    {
        if (model is not null && model.FindRootScope(op.Id) is not null)
        {
            var map = new Dictionary<string, string>();
            var complete = true;
            void AddNamed(string currentName, int nodeId)
            {
                var sym = model.FindSymbol(nodeId);
                if (sym is null) { complete = false; return; }
                if (TypeName(sym.Type) is { } t) map[currentName] = sym.IsArray ? t + "[]" : t;
            }
            void Level(IReadOnlyList<QStmt> stmts)
            {
                foreach (var s in stmts) if (s is QDecl d) AddNamed(d.Name, d.Id);
                foreach (var s in stmts)
                    switch (s)
                    {
                        case QFor f: AddNamed(f.Var, f.Id); Level(f.Body); break;
                        case QIf i: Level(i.Then); Level(i.Else); break;
                        case QWhile w: Level(w.Body); break;
                        case QRepeat r: Level(r.Body); break;
                        case QConjugate c: Level(c.Within); Level(c.Apply); break;
                    }
            }
            foreach (var p in op.Params) AddNamed(p.Name, p.Id);
            Level(op.Body);
            if (complete) return map;
            // a node the model has never seen (no Id hit, no derivation chain) — fall through to a rebuild
            // rather than emit from a partial map.
        }

        var sink = new List<QoraError>();                 // types only — any diagnostics are the validator's job
        var root = Passes.SymbolTableBuilder.Build(op, sink);
        var rebuilt = new Dictionary<string, string>();
        foreach (var s in root.AllSymbols())
            if (TypeName(s.Type) is { } t) rebuilt[s.SourceName] = s.IsArray ? t + "[]" : t;   // Int/Bit/Float/Angle (arrays marked); Qubit and untyped → null → skipped; the rebuild ran over the CURRENT tree, so its "source" IS the mangled program
        return rebuilt;
    }

    /// <summary>Render a condition for emission: the tree is bit-rewritten (<see cref="RewriteBits"/>)
    /// then printed.</summary>
    private static string RenderCond(QCond cond, Dictionary<string, string> varTypes) =>
        cond.Tree is null ? string.Empty : RenderNode(RewriteBits(cond.Tree, varTypes));

    /// <summary>
    /// The bit-condition adjustments, on the tree. WHY: OpenQASM has no logical <c>!</c> on a classical
    /// scalar, so a negated known-classical value <c>!x</c> becomes <c>x == 0</c>; and bit comparisons
    /// emit against BOOL literals — <c>r == 1</c> → <c>r == true</c>, <c>r != 0</c> → <c>r != false</c>
    /// (either operand order) — because the dominant consumer (Qiskit's qasm3 importer) accepts only
    /// <c>bit == const bool</c>. Applied bottom-up so every comparison under <c>&amp;&amp;</c>/<c>||</c>
    /// is rewritten, and the negation's <c>== 0</c> result immediately becomes <c>== false</c> for a bit.
    /// Ints and unknown names are left untouched.
    /// </summary>
    private static QNode RewriteBits(QNode node, Dictionary<string, string> varTypes)
    {
        node = node switch
        {
            QUnary u => u with { Operand = RewriteBits(u.Operand, varTypes) },
            QBinOp b => b with { Left = RewriteBits(b.Left, varTypes), Right = RewriteBits(b.Right, varTypes) },
            _ => node,
        };
        // `!x` is Qora's "x is zero/false" and OpenQASM has no logical NOT on a numeric value, so it is
        // ALWAYS rewritten to the comparison `x == 0` — a BLANKET rule, never conditional on being able to
        // type the operand. Gating it on a known type silently emitted `! ( sizeof(a) )` for a compound
        // operand (a `.Count`, a function call, arithmetic), which the target rejects
        // ("Invalid operator ! for IntegerLiteral"). A `bit` operand is then further rewritten to
        // `x == false` by the comparison handling below, exactly as before.
        if (node is QUnary { Op: "!", Operand: { } inner })
            node = new QBinOp("==", inner, new QNumLit(0));
        if (node is QBinOp { Op: "==" or "!=" } cmp)
        {
            if (TypeOfNode(cmp.Left, varTypes) == "bit" && cmp.Right is QNumLit { Value: 0 or 1 } rn)
                return cmp with { Right = new QLit(rn.Value == 1 ? "true" : "false") };
            if (TypeOfNode(cmp.Right, varTypes) == "bit" && cmp.Left is QNumLit { Value: 0 or 1 } ln)
                return cmp with { Left = new QLit(ln.Value == 1 ? "true" : "false") };
        }
        // NOTE: a WHOLE bit register needs NO adjustment here, and deliberately gets none. It can only have
        // reached an expression at all as `f == g` against another register of the same width (QSEM036), which
        // OpenQASM compares as bit patterns — exactly Qora's meaning — so it prints as written. Every reading
        // of a register AS A NUMBER is spelled `AsInt(f)` in the source and became a width-qualified
        // `uint[N](f)` in OpenQasmLowering, before this printer ever saw it.
        return node;
    }

    /// <summary>The emitted SCALAR type of a directly-referenced value — a bare scalar name, or one array
    /// element (whose type is the array's element type, stored as <c>"T[]"</c> under the array's name).
    /// A bare ARRAY name has no scalar type (a whole-register comparison is numeric, never bit-rewritten);
    /// compound expressions have no single lookup type.</summary>
    private static string? TypeOfNode(QNode node, Dictionary<string, string> varTypes) => node switch
    {
        QNameRef r => varTypes.TryGetValue(r.Name, out var t) && !t.EndsWith("[]") ? t : null,
        QIndexNode { Base: QNameRef b } => varTypes.TryGetValue(b.Name, out var t) && t.EndsWith("[]") ? t[..^2] : null,
        _ => null,
    };

    private static string EmitParam(QParam p) => p.Type switch
    {
        // bit is not a valid array base type (types.rst) — a bit[] parameter's only legal form is the
        // SIZED register, so monomorphization stamps its length exactly as it does for Qubit[].
        QType.Bit when p.IsArray && p.RegisterSize is int bits => $"bit[{bits}] {p.Name}",
        QType.Bit when p.IsArray => throw new InvalidOperationException(
            $"QINTERNAL: unspecialized bit[] parameter `{p.Name}` reached OpenQASM emission"),
        _ when p.Type != QType.Qubit && p.IsArray => $"mutable array[{TypeName(p.Type)}, #dim = 1] {p.Name}",
        QType.Int => $"int {p.Name}",
        QType.Bit => $"bit {p.Name}",
        QType.Float => $"float {p.Name}",
        QType.Angle => $"angle {p.Name}",
        QType.Qubit when p.RegisterSize is int n => $"qubit[{n}] {p.Name}",
        QType.Qubit when p.IsQubitArray => throw new InvalidOperationException(
            $"QINTERNAL: unspecialized Qubit[] parameter `{p.Name}` reached OpenQASM emission"),
        _ => $"qubit {p.Name}",
    };

    private static string RenderArg(QArg arg) => arg switch
    {
        QQubitArg q => $"{q.Reg}[{RenderNode(q.Index)}]",
        QTextArg t => RenderNode(t.Tree),
        _ => string.Empty,
    };

    private static string RenderExpr(QExpr expr) => expr switch
    {
        QMeasure m => $"measure {RenderNode(m.Target)}",
        QText t => RenderNode(t.Tree),
        QArrayLiteral literal => $"{{{string.Join(", ", literal.Elements.Select(RenderExpr))}}}",
        QArrayNew allocation => $"{{{string.Join(", ", Enumerable.Repeat(DefaultValue(allocation.ElementType), allocation.Length))}}}",
        _ => string.Empty,
    };

    /// <summary>
    /// Render an expression TREE as OpenQASM text — the emitter's own spelling, distinct from the
    /// canonical IR spelling (<see cref="QNodes.Render"/>): <c>.Count</c> becomes <c>sizeof(base)</c> and
    /// an indexed access glues (<c>q[i]</c>) — exactly the two rewrites the historical text path applied
    /// by regex over the stored text. Operators keep their single-space joins; no precedence parens are
    /// inserted (trees come from a paren-free grammar and rewrites substitute leaves only, so the in-order
    /// token run re-parses to the same structure).
    /// </summary>
    private static string RenderNode(QNode? node) => node switch
    {
        null => string.Empty,
        QNumLit n => n.Value.ToString(System.Globalization.CultureInfo.InvariantCulture),
        QLit l => l.Text,
        QNameRef r => r.Name,
        QMember { Member: "Count" } m => $"sizeof({RenderNode(m.Base)})",
        QMember m => $"{RenderNode(m.Base)} . {m.Member}",   // non-Count members never survive validation
        QUnary { Op: "!" } u => $"! ( {RenderNode(u.Operand)} )",
        QUnary u => $"{u.Op} {RenderOperand(u.Operand, parent: 5, isRight: true)}",
        QBinOp b => $"{RenderOperand(b.Left, Prec(b.Op))} {b.Op} {RenderOperand(b.Right, Prec(b.Op), isRight: true)}",
        QIndexNode i => $"{RenderNode(i.Base)}[{RenderNode(i.Index)}]",
        QCallNode c => $"{c.Name}({string.Join(", ", c.Args.Select(RenderNode))})",
        _ => string.Empty,
    };

    /// <summary>Render a binary/unary operand, parenthesizing ONLY when the emitted token run would
    /// re-parse to a different grouping than the tree: a child that binds strictly LOOSER than its parent
    /// (any side), or a SAME-precedence child on the RIGHT (the operators are left-associative, so
    /// <c>n == m == 0</c> re-parses as <c>(n == m) == 0</c> — the opposite of a tree holding
    /// <c>n == (m == 0)</c>). No PARSED tree holds either shape (the precedence parse builds left-leaning
    /// trees whose right children always bind strictly tighter), but a REWRITE can synthesize both —
    /// <see cref="RewriteBits"/> substitutes <c>m == 0</c> for <c>!m</c> wherever the negation sat.
    /// Natural trees never trigger this, so their emitted bytes are unchanged.</summary>
    private static string RenderOperand(QNode child, int parent, bool isRight = false) =>
        child is QBinOp cb && (Prec(cb.Op) < parent || (isRight && Prec(cb.Op) == parent))
            ? $"( {RenderNode(child)} )"
            : RenderNode(child);

    /// <summary>OpenQASM 3's (C-style) binding strength: <c>||</c> &lt; <c>&amp;&amp;</c> &lt; equality
    /// &lt; relational &lt; additive &lt; multiplicative — the ladder the emitted text re-parses under.</summary>
    private static int Prec(string op) => op switch
    {
        "||" => 1,
        "&&" => 2,
        "==" or "!=" => 3,
        "<" or "<=" or ">" or ">=" => 4,
        "+" or "-" => 5,
        "*" or "/" => 6,
        _ => 7,
    };

    private static string MapGate(string name) =>
        QoraGates.Names.TryGetValue(name, out var qasm) ? qasm : name.ToLowerInvariant();

    private static string? TypeName(QType? t) => t switch { QType.Int => "int", QType.Bit => "bit", QType.Float => "float", QType.Angle => "angle", _ => null };
}
